CREATE TABLE `admin_pay_order` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT,
  `status` int(11) NOT NULL DEFAULT '1' COMMENT '支付状态1-未支付  2-已支付',
  `order_list_id` bigint(11) DEFAULT NULL COMMENT '支付订单ID',
  `edu_student_id` bigint(11) NOT NULL COMMENT '学生ID',
  `goods_list_id` bigint(11) DEFAULT NULL COMMENT '商品ID',
  `amount` bigint(11) NOT NULL COMMENT '支付单金额',
  `admin_user_id` int(11) NOT NULL COMMENT '创建人ID',
  `remarks` varchar(1024) DEFAULT '' COMMENT '备注',
  `created_time` bigint(11) NOT NULL COMMENT '创建时间（时间戳）',
  `update_time` bigint(11) DEFAULT NULL COMMENT '更新时间（时间戳）',
  `del` int(11) NOT NULL DEFAULT '0',
  `admin_division_id` int(11) DEFAULT NULL COMMENT '平台',
  `del_admin_user_id` int(11) DEFAULT NULL COMMENT '取消支付单操作人ID',
  `is_bank_transfer` int(11) NOT NULL DEFAULT '1' COMMENT '是否开启银行转账：1关闭,2开启',
  PRIMARY KEY (`id`),
  KEY `admin_pay_order_wj_1` (`edu_student_id`) USING BTREE,
  KEY `admin_pay_order_wj_3` (`admin_user_id`) USING BTREE,
  KEY `admin_pay_order_wj_4` (`order_list_id`) USING BTREE,
  KEY `admin_pay_order_wj_2` (`goods_list_id`) USING BTREE,
  KEY `admin_pay_order_ibfk_5` (`admin_division_id`),
  KEY `admin_pay_order_wj_6` (`del_admin_user_id`),
  CONSTRAINT `admin_pay_order_ibfk_1` FOREIGN KEY (`edu_student_id`) REFERENCES `edu_student` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `admin_pay_order_ibfk_2` FOREIGN KEY (`goods_list_id`) REFERENCES `goods_list` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `admin_pay_order_ibfk_3` FOREIGN KEY (`admin_user_id`) REFERENCES `admin_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `admin_pay_order_ibfk_4` FOREIGN KEY (`order_list_id`) REFERENCES `order_list` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `admin_pay_order_ibfk_5` FOREIGN KEY (`admin_division_id`) REFERENCES `admin_division` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `admin_pay_order_wj_6` FOREIGN KEY (`del_admin_user_id`) REFERENCES `admin_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1168 DEFAULT CHARSET=utf8mb4 COMMENT='支付单'