CREATE TABLE `admin_user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `parent_id` int(11) DEFAULT NULL COMMENT '直属上级ID',
  `character_id` int(11) DEFAULT NULL COMMENT '角色ID',
  `department_id` bigint(11) NOT NULL DEFAULT '41' COMMENT '部门ID',
  `unionId` varchar(255) DEFAULT NULL COMMENT 'unionId',
  `user` varchar(128) CHARACTER SET utf8 NOT NULL COMMENT '用户名',
  `time` varchar(128) CHARACTER SET utf8 DEFAULT NULL COMMENT '创建时间',
  `entry_time` bigint(11) DEFAULT NULL COMMENT '入职时间',
  `dimission_time` bigint(11) DEFAULT NULL COMMENT '离职时间',
  `classin_id` varchar(128) CHARACTER SET utf8 DEFAULT NULL COMMENT '老师 classinid',
  `mobile` varchar(128) CHARACTER SET big5 DEFAULT NULL COMMENT '手机',
  `nick_name` varchar(128) CHARACTER SET utf8 DEFAULT NULL COMMENT '昵称',
  `del` int(11) NOT NULL DEFAULT '0' COMMENT '是否禁用 0 正常 1禁用',
  `del_time` varchar(128) CHARACTER SET utf8 DEFAULT NULL COMMENT '禁用时间',
  `crm_id` varchar(128) CHARACTER SET utf8 DEFAULT NULL COMMENT 'crmid',
  `weight` int(11) NOT NULL DEFAULT '0' COMMENT '是否有绩效0正常有绩效 1无绩效',
  `weight_auth` int(11) NOT NULL DEFAULT '0' COMMENT '权重开关',
  `password` varchar(128) CHARACTER SET utf8 NOT NULL DEFAULT 'yxuetongcom20200501' COMMENT '密码',
  `isadmin` int(11) NOT NULL DEFAULT '1' COMMENT '是否是管理员1 普通用户 2 管理员',
  `share_img` varchar(255) DEFAULT NULL COMMENT '分享图片',
  `wechat` varchar(255) DEFAULT NULL COMMENT '微信号',
  `dd_lock` int(11) NOT NULL DEFAULT '1' COMMENT '钉钉锁1 不可编辑 2通过钉钉添加',
  `office_email` varchar(128) DEFAULT NULL COMMENT '工作邮箱',
  `user_type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '用户来源 0:系统创建 1:moka',
  `is_pending` tinyint(1) DEFAULT '0' COMMENT '离职待办标记：0-无待办（默认）/1-有待办事项未完成',
  PRIMARY KEY (`id`),
  UNIQUE KEY `user` (`user`) USING BTREE,
  UNIQUE KEY `office_email` (`office_email`),
  KEY `character_id` (`character_id`) USING BTREE,
  KEY `admin_user_dc_id_1` (`department_id`) USING BTREE,
  KEY `mobile` (`mobile`) USING BTREE,
  KEY `idx_parent_id` (`parent_id`),
  KEY `idx_au_id` (`id`),
  CONSTRAINT `admin_user_ibfk_1` FOREIGN KEY (`department_id`) REFERENCES `admin_department_children` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `admin_user_ibfk_2` FOREIGN KEY (`character_id`) REFERENCES `admin_character` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=7712 DEFAULT CHARSET=utf8mb4 COMMENT='后台用户'