CREATE TABLE `admin_user_channel` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT,
  `admin_user_id` int(11) NOT NULL COMMENT '创建人用户ID',
  `responsible_admin_user_id` int(11) DEFAULT NULL COMMENT '协作人用户ID',
  `name` varchar(255) NOT NULL COMMENT '渠道名称',
  `channel_abbreviation` varchar(150) NOT NULL COMMENT '渠道简称( 简称命名规则：渠道名称拼音-渠道ID)',
  `type` int(255) NOT NULL COMMENT '渠道类型 1机构 2个人',
  `to_company` varchar(255) DEFAULT NULL COMMENT '所在公司',
  `to_post` varchar(255) DEFAULT NULL COMMENT '所在岗位',
  `category` varchar(255) NOT NULL COMMENT '渠道类别',
  `protocol_version` int(11) DEFAULT '1' COMMENT '协议版本 1 其他 2 22年通用 3 24年通用',
  `remark` varchar(1024) DEFAULT NULL COMMENT '渠道协议重要条款',
  `settlement` int(11) DEFAULT NULL COMMENT '结算方式 1公对公 2第三方',
  `collection_name` varchar(255) DEFAULT NULL COMMENT '收款账户名',
  `back_account` varchar(255) DEFAULT NULL COMMENT '银行账号',
  `back_name` varchar(255) DEFAULT NULL COMMENT '开户行',
  `protocol` int(11) DEFAULT NULL COMMENT '是否签署协议 1已签署 2未签署',
  `my_contract_company` varchar(255) DEFAULT NULL COMMENT '我放签约公司',
  `contract_time` bigint(11) DEFAULT NULL COMMENT '签约日期',
  `mobile` varchar(255) DEFAULT NULL COMMENT '手机号',
  `channel_phone` varchar(128) DEFAULT NULL COMMENT '渠道联系方式',
  `third_protocal` int(11) DEFAULT NULL COMMENT ' 是否签订第三方协议 1 是 2否',
  `id_card` varchar(255) DEFAULT NULL COMMENT '身份证',
  `created_time` bigint(11) NOT NULL COMMENT '创建时间',
  `update_time` bigint(11) NOT NULL COMMENT '更新时间',
  `del` int(11) NOT NULL DEFAULT '0',
  `maintainer_id` int(11) DEFAULT NULL COMMENT '维护人',
  `channel_tag` tinyint(4) DEFAULT NULL COMMENT '渠道标签:NULL 无、公司分配 1、个人拓展 2',
  PRIMARY KEY (`id`),
  KEY `admin_user_channel_wj_1` (`admin_user_id`) USING BTREE,
  KEY `admin_user_channel_wj_2` (`responsible_admin_user_id`) USING BTREE,
  KEY `idx_maintainer_id` (`maintainer_id`),
  CONSTRAINT `admin_user_channel_ibfk_1` FOREIGN KEY (`admin_user_id`) REFERENCES `admin_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `admin_user_channel_ibfk_2` FOREIGN KEY (`responsible_admin_user_id`) REFERENCES `admin_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=371 DEFAULT CHARSET=utf8mb4 COMMENT='渠道库'