CREATE TABLE `admin_category` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `name` varchar(128) NOT NULL COMMENT '名称',
  `admin_user_id` int(11) DEFAULT NULL COMMENT '创建人',
  `created_time` bigint(11) DEFAULT NULL COMMENT '创建时间',
  `update_time` bigint(11) DEFAULT NULL COMMENT '更新时间',
  `del` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否删除：0否，1是',
  `platform` tinyint(4) NOT NULL DEFAULT '0' COMMENT '平台：0-学通、1-科桥',
  `abbreviation` varchar(100) DEFAULT NULL COMMENT '公司简称',
  `tax_code` varchar(100) NOT NULL DEFAULT '' COMMENT '税号',
  `legal_entity` varchar(100) NOT NULL DEFAULT '' COMMENT '法人',
  `company_address` varchar(100) NOT NULL DEFAULT '' COMMENT '公司地址',
  `company_phone` varchar(100) NOT NULL DEFAULT '' COMMENT '公司电话',
  `invoice_category` varchar(1000) DEFAULT NULL COMMENT '发票类目',
  `tax_rate` decimal(5,2) DEFAULT NULL COMMENT '税率，0.00',
  `entity_status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '公司主体状态：0-停用、1-启用',
  `bank_status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '添加银行账户状态：0-未添加、1-已添加',
  `contract_seal_status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '合同印章配置状态：0-未配置、1-已配置',
  `use_status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '使用状态：0-停用、1-启用',
  `company_id` varchar(10) NOT NULL DEFAULT '0000' COMMENT '公司ID',
  `admin_category_account_id` int(11) DEFAULT NULL COMMENT '绑定的主体银行账户id',
  PRIMARY KEY (`id`),
  KEY `admin_category_sy_1` (`admin_user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=58 DEFAULT CHARSET=utf8 COMMENT='公司名称'