CREATE TABLE `cms_apply` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT,
  `my_user_id` bigint(20) DEFAULT NULL COMMENT '用户id',
  `cms_article_id` bigint(11) NOT NULL COMMENT '活动id',
  `type` int(11) NOT NULL DEFAULT '1' COMMENT '报名类型1系统报名2手动录入',
  `mobile` varchar(255) DEFAULT NULL COMMENT '报名手机',
  `name` varchar(255) DEFAULT NULL COMMENT '报名姓名',
  `student_grade` varchar(255) DEFAULT NULL COMMENT '学生年级',
  `remarks` varchar(255) DEFAULT NULL COMMENT '备注',
  `referrer` varchar(255) DEFAULT NULL COMMENT '推荐人',
  `first_referrer` varchar(255) DEFAULT NULL COMMENT '最初推荐人',
  `created_time` varchar(255) NOT NULL COMMENT '创建时间',
  `express_name` varchar(255) DEFAULT NULL COMMENT '快递名称',
  `express_number` varchar(255) DEFAULT NULL COMMENT '快递单号',
  `is_crm` int(11) NOT NULL DEFAULT '1' COMMENT '是否导入crm 1未导入 2已导入',
  `province` varchar(255) DEFAULT NULL COMMENT '省',
  `city` varchar(255) DEFAULT NULL COMMENT '市',
  `district` varchar(255) DEFAULT NULL COMMENT '区',
  `email` varchar(128) DEFAULT '' COMMENT '邮箱',
  `cms_apply_company` varchar(64) DEFAULT NULL COMMENT '公司',
  `cms_apply_position` varchar(64) DEFAULT NULL COMMENT '职位',
  `cms_unified_exam` int(4) DEFAULT NULL COMMENT '是否参考择校联考，枚举值（单选，1是/2否），选填',
  PRIMARY KEY (`id`),
  KEY `cms_apply_sy_1` (`cms_article_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=27981 DEFAULT CHARSET=utf8mb4 COMMENT='活动报名表'