CREATE TABLE `cms_article` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT,
  `cms_type_id` bigint(11) NOT NULL COMMENT '媒体类型id',
  `cms_section_id` bigint(11) NOT NULL COMMENT '栏目id',
  `goods_id` bigint(11) DEFAULT NULL COMMENT '商品id',
  `goods_ids` varchar(2048) DEFAULT NULL COMMENT '商品列表',
  `pay_type` int(11) NOT NULL DEFAULT '0' COMMENT '商品支付价格类型',
  `title` varchar(255) DEFAULT NULL COMMENT '标题',
  `description` varchar(255) DEFAULT NULL COMMENT '简介',
  `video` varchar(1024) DEFAULT NULL COMMENT '视频地址',
  `source` varchar(255) DEFAULT NULL COMMENT '媒体来源',
  `title_img_url` varchar(255) DEFAULT NULL COMMENT '头图',
  `details_url` varchar(255) DEFAULT NULL COMMENT '文章详情图片url',
  `event_start_time` varchar(255) DEFAULT NULL COMMENT '活动开始时间',
  `event_end_time` varchar(255) DEFAULT NULL COMMENT '活动结束时间',
  `address` varchar(1024) DEFAULT NULL COMMENT '地址',
  `web_url` varchar(1024) DEFAULT NULL COMMENT '外部页面链接url',
  `source_url` varchar(1024) DEFAULT NULL COMMENT '原文链接',
  `posted_at` varchar(255) DEFAULT NULL COMMENT '原文发布时间',
  `is_original` int(255) DEFAULT '2' COMMENT '1学通原创2非学通原创3其它原创',
  `idx` int(11) NOT NULL DEFAULT '0' COMMENT '头条',
  `readnums` int(11) NOT NULL DEFAULT '0' COMMENT '阅读数',
  `zannums` int(11) NOT NULL DEFAULT '0' COMMENT '点赞数',
  `admin_user_id` int(11) DEFAULT NULL COMMENT '创建人用户ID',
  `created_time` varchar(255) NOT NULL COMMENT '创建时间',
  `update_admin_user_id` int(11) DEFAULT NULL COMMENT '最后修改人ID',
  `update_time` varchar(255) NOT NULL COMMENT '更新时间',
  `sort` int(11) NOT NULL DEFAULT '0' COMMENT '排序',
  `num` int(11) NOT NULL DEFAULT '0' COMMENT '阅读数',
  `rel` int(11) NOT NULL DEFAULT '0' COMMENT '是否发布1已发布0未发布',
  `del` int(11) NOT NULL DEFAULT '0',
  `content` mediumtext COMMENT '富文本内容',
  PRIMARY KEY (`id`),
  KEY `goods_id` (`goods_id`) USING BTREE,
  KEY `created_time` (`created_time`(191)) USING BTREE,
  KEY `rel` (`rel`,`del`) USING BTREE,
  KEY `cms_type_id2` (`cms_type_id`) USING BTREE,
  KEY `cms_type_id3` (`admin_user_id`) USING BTREE,
  KEY `cms_article8` (`readnums`) USING BTREE,
  KEY `cms_article9` (`zannums`) USING BTREE,
  KEY `cms_article10` (`posted_at`(191)) USING BTREE,
  KEY `update_time` (`update_time`(191)) USING BTREE,
  KEY `cms_article11` (`cms_section_id`,`cms_type_id`,`update_time`(191),`del`) USING BTREE,
  CONSTRAINT `cms_article_section_id1` FOREIGN KEY (`cms_section_id`) REFERENCES `cms_section` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `cms_type_id2` FOREIGN KEY (`cms_type_id`) REFERENCES `cms_type` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `cms_type_id3` FOREIGN KEY (`admin_user_id`) REFERENCES `admin_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=428035 DEFAULT CHARSET=utf8mb4 COMMENT='媒体列表'