CREATE TABLE `customer_clue_info` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `customer_code` varchar(20) NOT NULL COMMENT '线索编码',
  `org` int(11) DEFAULT NULL COMMENT '归属事业部',
  `consult_campus_value` varchar(20) DEFAULT NULL COMMENT '咨询校区',
  `campus_value` varchar(20) DEFAULT NULL COMMENT '归属校区',
  `business_status` varchar(2) NOT NULL DEFAULT 'D' COMMENT '线索业务状态(A/B/C/D)',
  `customer_status` int(11) NOT NULL DEFAULT '100' COMMENT '线索小状态',
  `level1_channel_code` int(11) DEFAULT NULL COMMENT '一级渠道编码',
  `level2_channel_code` int(11) DEFAULT NULL COMMENT '二级渠道编码',
  `level3_channel_code` int(11) DEFAULT NULL COMMENT '三级渠道编码',
  `level4_channel_code` int(11) DEFAULT NULL COMMENT '四级渠道编码',
  `level5_channel_code` int(11) DEFAULT NULL COMMENT '五级渠道编码',
  `clue_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否名单线索 0-否 1-是',
  `customer_action` int(11) DEFAULT NULL COMMENT '市场客户动作',
  `channel_name` varchar(255) DEFAULT NULL COMMENT '运营渠道/渠道名称',
  `carrier` varchar(255) DEFAULT NULL COMMENT '载体',
  `keyword` varchar(255) DEFAULT NULL COMMENT '关键字',
  `utm_term` varchar(255) DEFAULT NULL COMMENT 'utm_term',
  `utm_source` varchar(255) DEFAULT NULL COMMENT 'utm_source',
  `utm_medium` varchar(255) DEFAULT NULL COMMENT 'utm_medium',
  `utm_content` varchar(255) DEFAULT NULL COMMENT 'utm_content',
  `introduce_user` varchar(255) DEFAULT NULL COMMENT '转介绍人',
  `customer_source` int(11) DEFAULT NULL COMMENT '线索来源',
  `utm_campaign` varchar(255) DEFAULT NULL COMMENT 'utm-campaign',
  `remark` varchar(512) NOT NULL DEFAULT '' COMMENT '备注',
  `sale_user_id` int(11) DEFAULT NULL COMMENT '当前销售人员Id',
  `tmk_user_id` int(11) DEFAULT NULL COMMENT '当前tmk人员Id',
  `deleted` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否删除 0 未删除 1 删除 默认是0',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间，默认当前时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间，默认当前时间',
  `create_by` int(11) DEFAULT NULL COMMENT '创建人',
  `update_by` int(11) DEFAULT NULL COMMENT '最后更新人',
  `remaining_recall_time` datetime DEFAULT NULL COMMENT '顾问抽回时间',
  `judgment_value` int(11) DEFAULT NULL COMMENT '线索判定',
  `current_process` int(11) DEFAULT NULL COMMENT '当前进展',
  `last_repeat_type` tinyint(4) DEFAULT NULL COMMENT '最新线索重复类型: 0-新线索 1-有效重复 2-无效重复',
  `sale_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否下发过顾问 0-未下发过 1-下发过',
  `repeat_customer_remark` varchar(512) DEFAULT NULL COMMENT '重复信息',
  `repeat_customer_time` timestamp NULL DEFAULT NULL COMMENT '重复信息时间',
  `last_follow_up_content` varchar(512) DEFAULT NULL COMMENT '最新跟进内容',
  `crm_id` varchar(15) DEFAULT NULL COMMENT 'crm_id ',
  `old_flag` int(11) DEFAULT '0' COMMENT '是否是老数据(历销数据)  0-否 1-是',
  `last_public_pool_time` datetime DEFAULT NULL COMMENT '最新置入公海时间',
  `special_channel` int(11) NOT NULL DEFAULT '0' COMMENT '特殊渠道 0:默认 1:渠道精推-个人渠道 2:渠道精推-机构渠道 3:渠道数据-个人渠道 4:渠道数据-机构渠道5, "用户转介绍" 6, "员工转介绍" 7, "个人渠道"',
  `charge_person_id` int(11) DEFAULT NULL COMMENT '负责人: 顾问 或者 校区负责人id',
  `sale_customer_action` int(11) DEFAULT NULL COMMENT '销售客户动作',
  `next_follow_up_time` datetime DEFAULT NULL COMMENT '最新跟进记录的下次跟进时间',
  `last_assign_sale_time` datetime DEFAULT NULL COMMENT '最新分配顾问时间',
  `before_charge_person_id` int(11) DEFAULT NULL COMMENT '前负责人',
  `sale_last_follow_up_time` datetime DEFAULT NULL COMMENT '顾问最新跟进时间',
  `first_create_time` datetime DEFAULT NULL COMMENT '线索首次创建时间',
  `lx_id` bigint(20) DEFAULT NULL COMMENT '历销ID',
  `first_create_by` int(11) DEFAULT NULL COMMENT '线索首次创建人',
  `last_update_time` datetime DEFAULT NULL COMMENT '最新更新时间',
  `introduce_user_id` int(11) DEFAULT NULL COMMENT '转介绍人Id',
  `follow_up_status` int(11) DEFAULT NULL COMMENT '跟进状态(克桥、克勒)',
  `customer_type` int(11) DEFAULT NULL COMMENT '客户类型（克桥、克勒）',
  `test_time` date DEFAULT NULL COMMENT '测试时间（克桥、克勒）',
  `visit_time` date DEFAULT NULL COMMENT '到访时间（克桥、克勒）',
  `pre_sale_id` int(11) DEFAULT NULL COMMENT '预负责人（克桥、克勒）',
  `first_assign_sale_time` datetime DEFAULT NULL COMMENT '首次下发顾问时间',
  `first_confirm_time` datetime DEFAULT NULL COMMENT '首次确认时间',
  `first_follow_up_time` datetime DEFAULT NULL COMMENT '首次跟进时间',
  `submitter_id` int(11) DEFAULT NULL COMMENT 'tmk 递交人',
  `transaction_time` date DEFAULT NULL COMMENT '成交时间  （克勒/科桥）',
  `tmk_follow_up_status` int(11) DEFAULT NULL COMMENT 'TMK跟进状态(克桥、克勒)',
  `tmk_next_follow_up_time` datetime DEFAULT NULL COMMENT 'TMK最新跟进记录的下次跟进时间',
  `tmk_judgment_value` int(11) DEFAULT NULL COMMENT 'TMK线索判定',
  `tmk_judgment_value_reason` int(11) DEFAULT NULL COMMENT 'TMK线索判定原因',
  `last_assign_tmk_time` datetime DEFAULT NULL COMMENT '最新分配TMK时间',
  `tmk_current_process` int(11) DEFAULT NULL COMMENT 'TMK当前进展(学通)',
  `create_by_dept_id` int(11) DEFAULT NULL COMMENT '录入人 所在部门ID',
  `sale_judgment_value_reason` int(11) DEFAULT NULL COMMENT '销售线索判定原因',
  `clue_flag_transform_time` datetime DEFAULT NULL COMMENT '转线索时间  记录暂不联系转线索时间',
  `sale_judgment_value_user_id` int(11) DEFAULT NULL COMMENT '有效线索判定（负责人ID）',
  `transferred_campus` varchar(255) DEFAULT NULL COMMENT '已流转校区（存储校区别名）',
  `special_campus_auto_assign_flag` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否特殊校区自动分配（0-否，1-是）',
  `special_campus_auto_assign_status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '特殊校区自动分配流程状态（0-未处理，1-流转中，2-已完成）',
  `quality_audit_status` tinyint(4) DEFAULT NULL COMMENT '质检审核状态 0-待审核 1-审核通过 2-已驳回',
  `extrapolate_remark` varchar(512) DEFAULT NULL COMMENT '外推备注（国际择校）',
  `last_follow_up_status` int(11) DEFAULT NULL COMMENT '最新跟进状态（择校）',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_customer_code` (`customer_code`) USING BTREE,
  KEY `idx_clue_flag` (`clue_flag`) USING BTREE,
  KEY `idx_level1_channel_code` (`level1_channel_code`) USING BTREE,
  KEY `idx_level2_channel_code` (`level2_channel_code`) USING BTREE,
  KEY `idx_level3_channel_code` (`level3_channel_code`) USING BTREE,
  KEY `idx_level4_channel_code` (`level4_channel_code`) USING BTREE,
  KEY `idx_level5_channel_code` (`level5_channel_code`) USING BTREE,
  KEY `idx_next_follow_up_time` (`next_follow_up_time`),
  KEY `idx_last_assign_sale_time` (`last_assign_sale_time`),
  KEY `idx_before_charge_person_id` (`before_charge_person_id`) USING BTREE,
  KEY `idx_sale_last_follow_up_time` (`sale_last_follow_up_time`),
  KEY `idx_first_create_time` (`first_create_time`),
  KEY `idx_lx_id` (`lx_id`),
  KEY `idx_charge_person_id` (`charge_person_id`),
  KEY `idx_customer_source` (`customer_source`) USING BTREE,
  KEY `idx_utm_source` (`utm_source`(191)) USING BTREE,
  KEY `idx_cci_customer_code_org` (`customer_code`,`org`,`deleted`),
  KEY `customer_clue_info_deleted_IDX` (`deleted`,`customer_code`),
  KEY `idx_first_assign_sale_time` (`first_assign_sale_time`),
  KEY `idx_business_status` (`business_status`,`customer_status`),
  KEY `idx_tmk_follow_up_status` (`tmk_follow_up_status`),
  KEY `idx_tmk_next_follow_up_time` (`tmk_next_follow_up_time`),
  KEY `idx_tmk_judgment_value` (`tmk_judgment_value`),
  KEY `idx_tmk_judgment_value_reason` (`tmk_judgment_value_reason`),
  KEY `idx_last_assign_tmk_time` (`last_assign_tmk_time`),
  KEY `idx_tmk_current_process` (`tmk_current_process`),
  KEY `idx_sale_judgment_value_reason` (`sale_judgment_value_reason`)
) ENGINE=InnoDB AUTO_INCREMENT=109556 DEFAULT CHARSET=utf8mb4 COMMENT='线索扩展表'