CREATE TABLE `customer_info` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `code` varchar(20) NOT NULL COMMENT '线索编码',
  `name` varchar(50) NOT NULL COMMENT '姓名',
  `en_name` varchar(20) DEFAULT NULL COMMENT '英文姓名',
  `gender` tinyint(4) DEFAULT NULL COMMENT '性别 0-未知 1-男  2-女',
  `age` int(11) DEFAULT '0' COMMENT '年龄',
  `birthday` datetime DEFAULT NULL COMMENT '生日',
  `deleted` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否删除 0 未删除 1 删除 默认是0',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间，默认当前时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间，默认当前时间',
  `create_by` int(11) DEFAULT NULL COMMENT '创建人',
  `update_by` int(11) DEFAULT NULL COMMENT '最后更新人',
  `repeat_type` tinyint(4) DEFAULT NULL COMMENT '原始线索重复类型: 0-新线索 1-有效重复 2-无效重复',
  `student_code` varchar(20) DEFAULT NULL COMMENT '学生编码(废弃不使用,所有的线索编码对应的是customer_code)',
  `old_flag` int(11) DEFAULT '0' COMMENT '是否是老数据(历销数据) 0-否 1-是',
  `crm_id` varchar(15) DEFAULT NULL COMMENT 'CRM系统业务主键',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_code` (`code`) USING BTREE,
  KEY `idx_name` (`name`) USING BTREE,
  KEY `idx_create_time` (`create_time`),
  KEY `customer_info_deleted_IDX` (`deleted`,`create_time`) USING BTREE,
  KEY `idx_create_by` (`create_by`)
) ENGINE=InnoDB AUTO_INCREMENT=109565 DEFAULT CHARSET=utf8mb4 COMMENT='线索主表'