CREATE TABLE `customers_new_sign_returned_info` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `campus_value` varchar(10) DEFAULT NULL COMMENT '线索归属校区别名',
  `order_id` int(11) DEFAULT NULL COMMENT '订单ID',
  `pay_id` int(11) DEFAULT NULL COMMENT '支付单ID',
  `returned_id` int(11) DEFAULT NULL COMMENT '回款ID ',
  `returned_status_name` varchar(255) NOT NULL COMMENT '回款单状态  1审批中  2驳回  3已通过',
  `returned_status` tinyint(4) NOT NULL COMMENT '回款单状态  1 审批中 2驳回  3 已通过',
  `customer_code` varchar(20) DEFAULT NULL COMMENT '线索编码',
  `student_name` varchar(50) DEFAULT NULL COMMENT '学生名称',
  `student_id` int(11) DEFAULT NULL COMMENT '学生ID',
  `student_type` varchar(15) DEFAULT NULL COMMENT '学生类型',
  `curriculum_system` varchar(15) DEFAULT NULL COMMENT '课程体系',
  `expense_type` varchar(15) DEFAULT NULL COMMENT '费用类型',
  `order_type` varchar(15) DEFAULT NULL COMMENT '订单类型',
  `order_type_id` tinyint(4) DEFAULT NULL COMMENT '订单类型ID',
  `order_create_time` datetime DEFAULT NULL COMMENT '订单创建时间',
  `product_num` varchar(15) DEFAULT NULL COMMENT '产品数量',
  `order_total_amount` decimal(18,4) DEFAULT NULL COMMENT '订单总金额',
  `order_discount_factor` decimal(18,4) DEFAULT NULL COMMENT '订单折扣系数',
  `order_actual_amount` decimal(18,4) DEFAULT NULL COMMENT '订单实际金额',
  `returned_type` varchar(15) DEFAULT NULL COMMENT '回款类型',
  `returned_type_id` tinyint(4) DEFAULT NULL COMMENT '回款类型ID',
  `returned_date` datetime DEFAULT NULL COMMENT '回款日期',
  `returned_account_name` varchar(50) DEFAULT NULL COMMENT '回款账户名',
  `returned_create_by` int(11) DEFAULT NULL COMMENT '回款创建人ID',
  `returned_create_by_name` varchar(30) DEFAULT NULL COMMENT '回款创建人名称',
  `returned_amount` decimal(18,4) DEFAULT NULL COMMENT '回款金额',
  `customer_create_by` int(11) DEFAULT NULL COMMENT '线索录入人ID',
  `customer_create_by_name` varchar(30) DEFAULT NULL COMMENT '线索录入人名称',
  `first_create_by` int(11) DEFAULT NULL COMMENT '最初录入人ID',
  `first_create_by_name` varchar(30) DEFAULT NULL COMMENT '最初录入人名称',
  `customer_create_time` datetime DEFAULT NULL COMMENT '有效创建时间（线索）',
  `level1_channel_name` varchar(15) DEFAULT NULL COMMENT '一级渠道名称',
  `level2_channel_name` varchar(15) DEFAULT NULL COMMENT '二级渠道名称',
  `level3_channel_name` varchar(15) DEFAULT NULL COMMENT '三级渠道名称',
  `level4_channel_name` varchar(15) DEFAULT NULL COMMENT '四级渠道名称',
  `level1_channel_code` int(11) DEFAULT NULL COMMENT '一级渠道Code',
  `level2_channel_code` int(11) DEFAULT NULL COMMENT '二级渠道Code',
  `level3_channel_code` int(11) DEFAULT NULL COMMENT '三级渠道Code',
  `level4_channel_code` int(11) DEFAULT NULL COMMENT '四级渠道Code',
  `customer_keyword` varchar(255) DEFAULT NULL COMMENT '关键字',
  `now_date` varchar(15) DEFAULT NULL COMMENT '年月日',
  `now_month` varchar(15) DEFAULT NULL COMMENT '年月',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `delete_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否删除 0否  1是',
  `collection_admin_user_id` int(11) DEFAULT NULL COMMENT '回款收款人ID',
  `collection_admin_user_name` varchar(30) DEFAULT NULL COMMENT '回款收款人名称',
  `subject_price` varchar(50) DEFAULT NULL COMMENT '科目标准单价',
  `product_name` varchar(50) NOT NULL COMMENT '产品名称',
  `customer_source` int(11) DEFAULT NULL COMMENT '线索来源',
  `collection_user_campus_value` varchar(30) NOT NULL COMMENT '收款人归属校区',
  `customer_action` tinyint(4) DEFAULT NULL COMMENT '客户动作',
  PRIMARY KEY (`id`),
  KEY `idx_now_date` (`now_date`),
  KEY `idx_now_month` (`now_month`)
) ENGINE=InnoDB AUTO_INCREMENT=194443 DEFAULT CHARSET=utf8mb4 COMMENT='新签转化率 线索订单回款明细表'