CREATE TABLE `edu_teacher_handbook` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键 id',
  `record_id` varchar(64) NOT NULL COMMENT '飞书记录ID',
  `teacher_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '老师 id',
  `english_name` varchar(255) NOT NULL DEFAULT '' COMMENT '英文名',
  `avatar` varchar(100) NOT NULL DEFAULT '' COMMENT '师资册头像',
  `intro` text COMMENT '个人简介',
  `style` varchar(3000) NOT NULL DEFAULT '' COMMENT '授课风格',
  `tags` varchar(3000) NOT NULL DEFAULT '' COMMENT '教师标签',
  `degree_info` varchar(3000) NOT NULL DEFAULT '' COMMENT '学历/提分率/获奖率',
  `experience_info` varchar(500) NOT NULL DEFAULT '' COMMENT '学生数/授课经验/时长',
  `student_number` varchar(64) NOT NULL DEFAULT '' COMMENT '学生数',
  `teaching_duration` varchar(64) NOT NULL DEFAULT '' COMMENT '授课时长',
  `teaching_experience` varchar(64) NOT NULL DEFAULT '' COMMENT '授课经验',
  `subjects` varchar(3000) NOT NULL DEFAULT '' COMMENT '可授科目',
  `features` text COMMENT '教学特色',
  `achievements` text COMMENT '教学成就',
  `lark_status` varchar(16) NOT NULL DEFAULT '' COMMENT '飞书师资册状态',
  `handbook_status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '师资册状态：0-未完成，1-已完成',
  `deleted` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否删除 0 未删除 1 删除 默认是0',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间，默认当前时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间，默认当前时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_teacherId` (`teacher_id`),
  KEY `idx_recordId` (`record_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=92 DEFAULT CHARSET=utf8mb4 COMMENT='老师师资册信息表'