CREATE TABLE `edu_adjust_study` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT,
  `valid` int(11) NOT NULL COMMENT '审批状态1.待审批;2.已通过;3.已驳回;4.已撤销',
  `adjust_status` int(11) NOT NULL DEFAULT '1' COMMENT '调课状态1待调整;2系统调整成功;3系统调整失败;4手动调整成功',
  `adjust_type` int(11) NOT NULL COMMENT '调课申请类型1编辑课程 2调课 3取消排课',
  `old_study_id` bigint(11) NOT NULL COMMENT '调课前的排课ID',
  `new_study_id` bigint(11) DEFAULT NULL COMMENT '调课后的排课ID',
  `remarks` varchar(1024) DEFAULT '' COMMENT '调整调课原因',
  `fail_reason` varchar(1024) DEFAULT NULL COMMENT '调课失败原因-系统写入',
  `admin_user_id` int(11) NOT NULL COMMENT '创建人ID',
  `operator_admin_user_id` int(11) DEFAULT NULL COMMENT '操作人',
  `created_time` bigint(11) NOT NULL COMMENT '创建时间',
  `update_time` bigint(11) DEFAULT NULL COMMENT '更新时间',
  `del` int(11) NOT NULL DEFAULT '0' COMMENT '0正常1删除',
  `adjust_source` int(11) NOT NULL DEFAULT '1' COMMENT '调课申请来源 1 默认规则 2老师3学生',
  PRIMARY KEY (`id`),
  KEY `edu_adjust_study_1` (`old_study_id`) USING BTREE,
  KEY `edu_adjust_study_2` (`new_study_id`) USING BTREE,
  KEY `edu_adjust_study_3` (`admin_user_id`) USING BTREE,
  KEY `edu_adjust_study_4` (`operator_admin_user_id`) USING BTREE,
  CONSTRAINT `edu_adjust_study_ibfk_1` FOREIGN KEY (`old_study_id`) REFERENCES `edu_study` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_adjust_study_ibfk_2` FOREIGN KEY (`new_study_id`) REFERENCES `edu_study` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_adjust_study_ibfk_3` FOREIGN KEY (`admin_user_id`) REFERENCES `admin_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_adjust_study_ibfk_4` FOREIGN KEY (`operator_admin_user_id`) REFERENCES `admin_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=684 DEFAULT CHARSET=utf8mb4 COMMENT='调课申请'