CREATE TABLE `edu_goods` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT,
  `admin_division` int(11) DEFAULT '1' COMMENT 'admin_division',
  `edu_campus_id` bigint(11) DEFAULT NULL COMMENT '一级校区id',
  `edu_goods_year_id` int(11) DEFAULT NULL COMMENT '年份',
  `edu_goods_section_id` bigint(11) NOT NULL DEFAULT '4' COMMENT '产品分类ID',
  `order_contract_template_id` bigint(11) DEFAULT NULL COMMENT '合同模板ID',
  `edu_student_type_id` bigint(11) DEFAULT NULL COMMENT '学生类型ID',
  `name` varchar(255) NOT NULL COMMENT '产品名称',
  `introduce` varchar(1024) DEFAULT NULL COMMENT '产品介绍',
  `order_pattern_id` int(11) NOT NULL COMMENT '产品类型(订单模式ID)',
  `goods_price` int(11) NOT NULL COMMENT '产品价格（精确到分）',
  `discount` int(11) NOT NULL DEFAULT '100' COMMENT '产品最低折扣0-100',
  `price_id` bigint(11) NOT NULL COMMENT '产品标准单价ID',
  `admin_user_id` int(11) NOT NULL COMMENT '产品添加人ID',
  `is_test` int(11) NOT NULL DEFAULT '1' COMMENT '试听课1正常课程 2试听课',
  `is_approval` int(11) NOT NULL DEFAULT '1' COMMENT '是否强制走高级审批1不强制 2强制',
  `remarks` varchar(2048) DEFAULT NULL COMMENT '备注',
  `is_study_abroad` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否留学产品 0-否 1-是',
  `created_time` bigint(20) NOT NULL,
  `update_time` bigint(20) NOT NULL,
  `del` int(255) NOT NULL DEFAULT '0',
  `rel` int(255) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `admin_user_id_assistant` (`admin_user_id`) USING BTREE,
  KEY `edu_goods2` (`price_id`) USING BTREE,
  KEY `edu_goods3` (`order_pattern_id`) USING BTREE,
  KEY `edu_goods4` (`edu_goods_section_id`) USING BTREE,
  KEY `edu_goods5` (`order_contract_template_id`) USING BTREE,
  KEY `edu_goods6` (`edu_student_type_id`) USING BTREE,
  KEY `edu_goods7` (`admin_division`) USING BTREE,
  KEY `edu_goods8` (`edu_goods_year_id`) USING BTREE,
  KEY `edu_goods9` (`edu_campus_id`),
  CONSTRAINT `edu_goods1` FOREIGN KEY (`admin_user_id`) REFERENCES `admin_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_goods2` FOREIGN KEY (`price_id`) REFERENCES `edu_course_exam_subject_name_price` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_goods3` FOREIGN KEY (`order_pattern_id`) REFERENCES `order_pattern` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_goods4` FOREIGN KEY (`edu_goods_section_id`) REFERENCES `edu_goods_section` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_goods5` FOREIGN KEY (`order_contract_template_id`) REFERENCES `order_contract_template` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_goods6` FOREIGN KEY (`edu_student_type_id`) REFERENCES `edu_student_type` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_goods7` FOREIGN KEY (`admin_division`) REFERENCES `admin_division` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_goods8` FOREIGN KEY (`edu_goods_year_id`) REFERENCES `edu_goods_year` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_goods9` FOREIGN KEY (`edu_campus_id`) REFERENCES `edu_campus` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=4260 DEFAULT CHARSET=utf8mb4 COMMENT='产品-主表'