CREATE TABLE `edu_student` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '学生ID',
  `type` int(11) NOT NULL DEFAULT '1' COMMENT '类型1学通学生2学通客户3科桥学生4科桥客户',
  `my_user_id` bigint(11) DEFAULT NULL COMMENT '注册用户ID',
  `classin_id` varchar(100) DEFAULT NULL COMMENT 'classinid',
  `classin_phone` bigint(11) DEFAULT NULL COMMENT 'classin手机',
  `edu_student_status_id` bigint(11) NOT NULL DEFAULT '1' COMMENT '学生状态IDedu_student_status',
  `edu_student_type_id` bigint(11) DEFAULT NULL COMMENT '学生类型ID',
  `edu_student_type_project_id` bigint(11) DEFAULT NULL COMMENT '报读项目ID',
  `name` varchar(255) NOT NULL COMMENT '学生姓名',
  `pinyin_name` varchar(255) DEFAULT NULL COMMENT '拼音',
  `english_name` varchar(255) DEFAULT NULL COMMENT '英文名',
  `user_img` varchar(255) DEFAULT NULL COMMENT '用户头像',
  `birth` bigint(11) DEFAULT NULL COMMENT '生日（时间戳）',
  `email` varchar(255) DEFAULT NULL COMMENT '邮箱',
  `phone` bigint(11) DEFAULT NULL COMMENT '学生手机',
  `sex` int(11) NOT NULL DEFAULT '3' COMMENT '性别1男2女3其他',
  `institutions` varchar(1024) DEFAULT NULL COMMENT '目标院校',
  `ingrade` varchar(255) DEFAULT NULL COMMENT '在读年级',
  `direction` varchar(255) DEFAULT NULL COMMENT '专业方向',
  `characters` varchar(255) DEFAULT NULL COMMENT '学生性格',
  `inschool` varchar(255) DEFAULT NULL COMMENT '在读学校',
  `examination_time` bigint(11) DEFAULT NULL COMMENT '考试时间（时间戳）',
  `achievement` varchar(255) DEFAULT NULL COMMENT '语言成绩',
  `abroad` varchar(255) DEFAULT NULL COMMENT '留学国家',
  `examination` varchar(255) DEFAULT NULL COMMENT '考试局',
  `campus_school_id` bigint(11) DEFAULT NULL COMMENT '所属校区ID',
  `firstclass_time` bigint(11) DEFAULT NULL COMMENT '首次课时间（时间戳）',
  `remarks` varchar(1024) DEFAULT NULL COMMENT '备注',
  `admin_user_id` int(11) DEFAULT NULL COMMENT '创建人ID',
  `certificates` varchar(255) DEFAULT NULL COMMENT '证件号码',
  `certificates_type` int(11) DEFAULT NULL COMMENT '证件类型edu_student_certificates_type',
  `certificates_valid` bigint(11) DEFAULT NULL COMMENT '证件有效期（时间戳）',
  `stop_course_time` bigint(11) DEFAULT NULL COMMENT '最近一次停课时间',
  `stop_course_remarks` varchar(1024) DEFAULT NULL COMMENT '最近一次停课原因',
  `in_school_time` bigint(11) DEFAULT NULL COMMENT '入校时间',
  `transfer_school_time` bigint(11) DEFAULT NULL COMMENT '转校时间',
  `exit_school_time` bigint(11) DEFAULT NULL COMMENT '退学时间',
  `created_time` bigint(11) NOT NULL,
  `update_time` bigint(11) NOT NULL,
  `del` int(255) NOT NULL DEFAULT '0',
  `rel` int(255) NOT NULL DEFAULT '0',
  `bank_account` varchar(255) DEFAULT NULL COMMENT '银行账号',
  `bank_account_status` int(11) NOT NULL DEFAULT '0' COMMENT '银行账号是否注销 0初始化 1有效 2注销（无效）',
  `update_my_user_id` bigint(11) DEFAULT NULL COMMENT '通过小程序更新数据时的微信用户注册id',
  `my_user_update_time` bigint(11) DEFAULT NULL COMMENT '通过小程序更新数据的时间',
  `phone_back` bigint(11) DEFAULT NULL COMMENT 'phone备份',
  `parent_info` varchar(255) DEFAULT NULL COMMENT '家长情况',
  `student_code` varchar(20) DEFAULT NULL COMMENT '学生编码',
  `org` int(11) DEFAULT NULL COMMENT '组织 0-学通 1-科桥 2-科勒',
  PRIMARY KEY (`id`),
  UNIQUE KEY `edu_student1` (`my_user_id`,`type`) USING BTREE,
  UNIQUE KEY `edu_student7` (`type`,`my_user_id`) USING BTREE,
  KEY `edu_student2` (`campus_school_id`) USING BTREE,
  KEY `edu_student3` (`edu_student_type_id`) USING BTREE,
  KEY `edu_student4` (`edu_student_status_id`) USING BTREE,
  KEY `edu_student_wj_5` (`edu_student_type_project_id`) USING BTREE,
  KEY `edu_student_wj_6` (`certificates_type`) USING BTREE,
  KEY `edu_student_wj_7_idx` (`update_my_user_id`),
  KEY `edu_student_wj_7` (`update_my_user_id`) USING BTREE,
  KEY `idx_student_code` (`student_code`),
  CONSTRAINT `edu_student1` FOREIGN KEY (`my_user_id`) REFERENCES `my_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_student2` FOREIGN KEY (`campus_school_id`) REFERENCES `edu_campus_school` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_student3` FOREIGN KEY (`edu_student_type_id`) REFERENCES `edu_student_type` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_student4` FOREIGN KEY (`edu_student_status_id`) REFERENCES `edu_student_status` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_student_wj_5` FOREIGN KEY (`edu_student_type_project_id`) REFERENCES `edu_student_type_project` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_student_wj_6` FOREIGN KEY (`certificates_type`) REFERENCES `edu_student_certificates_type` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_student_wj_7` FOREIGN KEY (`update_my_user_id`) REFERENCES `my_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=196052 DEFAULT CHARSET=utf8mb4 COMMENT='学生'