CREATE TABLE `edu_feed_teacher` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT,
  `status` int(11) NOT NULL DEFAULT '1' COMMENT '反馈状态1草稿2已发送3已反馈4驳回',
  `study_id` bigint(11) DEFAULT NULL COMMENT '排课ID',
  `keqiao_study_id` bigint(11) DEFAULT NULL COMMENT '科桥排课ID',
  `course_time` bigint(11) DEFAULT NULL COMMENT '授课时间（时间戳）',
  `course_time_end` bigint(11) DEFAULT NULL COMMENT '授课结束时间（时间戳）',
  `course_name` varchar(1024) DEFAULT NULL COMMENT '授课名称',
  `course_content` varchar(1024) DEFAULT NULL COMMENT '授课内容',
  `task_time` varchar(255) DEFAULT NULL COMMENT '预计作业完成时间（字符）',
  `student_id` bigint(11) NOT NULL COMMENT '学生ID',
  `admin_user_id` int(11) NOT NULL COMMENT '创建人老师ID',
  `tk_knowledge_ids` varchar(1024) DEFAULT NULL COMMENT '知识点ids',
  `edu_course_exam_subject_name_id` bigint(11) DEFAULT NULL COMMENT '科目名称(四级)ID',
  `content` mediumtext NOT NULL COMMENT '反馈内容',
  `classroom_learning_num` int(11) DEFAULT NULL COMMENT '课堂学习表现（评分）',
  `classroom_learning_text` varchar(1024) DEFAULT NULL COMMENT '课堂学习表现（说明）',
  `classroom_exercises_num` int(11) DEFAULT NULL COMMENT '课堂练习（评分）',
  `classroom_exercises_text` varchar(1024) DEFAULT NULL COMMENT '课堂练习（说明）',
  `remarks` varchar(2048) DEFAULT NULL COMMENT '备注',
  `created_time` bigint(11) NOT NULL COMMENT '创建时间',
  `update_time` bigint(11) NOT NULL,
  `del` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `edu_feed_teacher1` (`study_id`) USING BTREE,
  KEY `edu_feed_teacher2` (`student_id`) USING BTREE,
  KEY `edu_feed_teacher3` (`admin_user_id`) USING BTREE,
  KEY `edu_feed_teacher_ibfk_4_idx` (`keqiao_study_id`),
  KEY `edu_feed_teacher_wj_5` (`edu_course_exam_subject_name_id`),
  CONSTRAINT `edu_feed_teacher_ibfk_1` FOREIGN KEY (`study_id`) REFERENCES `edu_study` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_feed_teacher_ibfk_2` FOREIGN KEY (`student_id`) REFERENCES `edu_student` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_feed_teacher_ibfk_3` FOREIGN KEY (`admin_user_id`) REFERENCES `admin_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_feed_teacher_ibfk_4` FOREIGN KEY (`keqiao_study_id`) REFERENCES `keqiao_study` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_feed_teacher_wj_5` FOREIGN KEY (`edu_course_exam_subject_name_id`) REFERENCES `edu_course_exam_subject_name` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=53685 DEFAULT CHARSET=utf8mb4 COMMENT='课程反馈(老师)'