CREATE TABLE `edu_achievement` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT,
  `edu_student_id` bigint(11) NOT NULL COMMENT '学生ID',
  `type` bigint(11) NOT NULL COMMENT '考试类型',
  `achievement_source` int(11) DEFAULT NULL COMMENT '成绩来源 1学通内部 2外部3暂无考试',
  `time_start` bigint(11) NOT NULL COMMENT '考试开始时间（时间戳）',
  `time_end` bigint(11) NOT NULL COMMENT '考试结束时间（时间戳）',
  `edu_course_id` bigint(11) NOT NULL COMMENT '课程',
  `edu_course_exam_id` bigint(11) NOT NULL COMMENT '考试局',
  `edu_course_exam_subject_id` bigint(11) NOT NULL COMMENT '科目',
  `edu_course_exam_subject_name_id` bigint(11) NOT NULL COMMENT '科目名称',
  `edu_course_exam_module_id` int(11) DEFAULT NULL COMMENT '五级模块ID',
  `achievement` varchar(255) DEFAULT NULL COMMENT '考试成绩',
  `evaluate` varchar(2048) DEFAULT NULL COMMENT '评价',
  `admin_user_id` int(11) NOT NULL COMMENT '创建人ID',
  `remarks` varchar(2048) DEFAULT NULL COMMENT '备注',
  `created_time` bigint(11) NOT NULL COMMENT '创建时间',
  `update_time` bigint(11) DEFAULT NULL,
  `rel` int(11) NOT NULL DEFAULT '0' COMMENT '是否发布0未发布1已发布',
  `del` int(11) NOT NULL DEFAULT '0' COMMENT '是否作废0正常 1作废',
  `apply_status` varchar(255) DEFAULT NULL COMMENT '当前记录是否报考',
  `first_achievement` varchar(255) DEFAULT NULL COMMENT '首考成绩',
  `student_feedback` varchar(255) DEFAULT NULL COMMENT '是否达到学员预期',
  `edu_achievement_collect_task_id` bigint(11) DEFAULT NULL COMMENT '测试成绩-分数采集任务表ID',
  `class_hours` varchar(128) DEFAULT NULL COMMENT '课时数',
  `exams_year_season_type_id` int(11) DEFAULT NULL COMMENT '考试类型ID',
  `exams_year_quarter_id` bigint(11) DEFAULT NULL COMMENT '年度报考-季度ID',
  `award` varchar(255) DEFAULT NULL COMMENT '奖项',
  `firsted` int(11) DEFAULT '0' COMMENT '是否首考0不是 1是（大考类型）',
  PRIMARY KEY (`id`),
  KEY `edu_achievement_wj_1` (`edu_student_id`) USING BTREE,
  KEY `edu_achievement_wj_2` (`type`) USING BTREE,
  KEY `edu_achievement_wj_3` (`edu_course_id`) USING BTREE,
  KEY `edu_achievement_wj_4` (`edu_course_exam_id`) USING BTREE,
  KEY `edu_achievement_wj_5` (`edu_course_exam_subject_id`) USING BTREE,
  KEY `edu_achievement_wj_6` (`edu_course_exam_subject_name_id`) USING BTREE,
  KEY `edu_achievement_wj_7` (`admin_user_id`) USING BTREE,
  KEY `edu_achievement_sy_8` (`edu_achievement_collect_task_id`),
  KEY `edu_achievement_sy_9` (`exams_year_quarter_id`),
  KEY `edu_achievement_sy_1` (`exams_year_season_type_id`),
  CONSTRAINT `edu_achievement_ibfk_1` FOREIGN KEY (`edu_student_id`) REFERENCES `edu_student` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_achievement_ibfk_2` FOREIGN KEY (`type`) REFERENCES `edu_achievement_type` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_achievement_ibfk_3` FOREIGN KEY (`edu_course_id`) REFERENCES `edu_course` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_achievement_ibfk_4` FOREIGN KEY (`edu_course_exam_id`) REFERENCES `edu_course_exam` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_achievement_ibfk_5` FOREIGN KEY (`edu_course_exam_subject_id`) REFERENCES `edu_course_exam_subject` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_achievement_ibfk_6` FOREIGN KEY (`edu_course_exam_subject_name_id`) REFERENCES `edu_course_exam_subject_name` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_achievement_ibfk_7` FOREIGN KEY (`admin_user_id`) REFERENCES `admin_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_achievement_wj_10` FOREIGN KEY (`exams_year_season_type_id`) REFERENCES `exams_year_season_type` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_achievement_wj_8` FOREIGN KEY (`edu_achievement_collect_task_id`) REFERENCES `edu_achievement_collect_task` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_achievement_wj_9` FOREIGN KEY (`exams_year_quarter_id`) REFERENCES `exams_year_quarter` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=11748 DEFAULT CHARSET=utf8mb4 COMMENT='测试成绩-成绩'