CREATE TABLE `edu_study` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT,
  `status` int(11) NOT NULL DEFAULT '1' COMMENT '课程状态1初始化2已结课',
  `type` int(11) NOT NULL DEFAULT '1' COMMENT '课程类型1线下课2网课3活动4classin网课',
  `test_course` int(11) NOT NULL DEFAULT '1' COMMENT '(废弃)试听课1正常课程2试听课',
  `class_time_start` bigint(11) NOT NULL COMMENT '上课开始时间（时间戳）',
  `class_time_end` bigint(11) DEFAULT NULL COMMENT '上课结束时间（时间戳）',
  `class_week` int(11) DEFAULT NULL COMMENT '星期0~6',
  `class_hour` decimal(4,2) NOT NULL COMMENT '课时数',
  `edu_campus_school_class_id` bigint(11) DEFAULT NULL COMMENT '教室ID',
  `edu_course_exam_subject_name_id` bigint(11) NOT NULL COMMENT '科目名称ID',
  `edu_class_type_id` bigint(11) DEFAULT NULL COMMENT '班级类型ID',
  `edu_admin_user_id` int(11) NOT NULL COMMENT '上课老师ID',
  `admin_user_id` int(11) NOT NULL COMMENT '操作人ID',
  `english_teaching` varchar(255) NOT NULL DEFAULT '1' COMMENT '是否英语授课1不是2是',
  `jingsai_teaching` int(11) NOT NULL DEFAULT '1' COMMENT '是否竞赛 1不是 2是',
  `trial_teaching` int(11) NOT NULL DEFAULT '1' COMMENT '是否是试听课:1不是，2是',
  `created_time` bigint(11) NOT NULL COMMENT '创建时间',
  `update_time` bigint(11) NOT NULL COMMENT '更新时间',
  `del` int(11) NOT NULL DEFAULT '0' COMMENT '取消排课0正常1删除',
  `is_send` int(11) NOT NULL DEFAULT '1' COMMENT '老师课程提醒 1-未发送 2-提前150分钟发送  3-提现30分钟发送',
  `is_user_send` int(11) NOT NULL DEFAULT '1' COMMENT '学生及家长课程提醒 1-未发送 2-提前150分钟发送  ',
  `is_video` int(11) NOT NULL DEFAULT '0' COMMENT '是否录课0不录课 1录课',
  `video_url` varchar(1024) DEFAULT NULL COMMENT '上课视频地址',
  `remarks` varchar(1024) DEFAULT NULL COMMENT '备注',
  `classin_course_id` varchar(100) DEFAULT NULL COMMENT 'classin 课程ID',
  `classin_class_id` varchar(100) DEFAULT NULL COMMENT 'classin 课节ID',
  `update_admin_user_id` int(11) DEFAULT NULL COMMENT '更新人ID',
  `complete_time` bigint(11) DEFAULT NULL COMMENT '结课时间',
  PRIMARY KEY (`id`),
  KEY `edu_study3` (`edu_class_type_id`) USING BTREE,
  KEY `edu_study4` (`edu_admin_user_id`) USING BTREE,
  KEY `edu_study2` (`admin_user_id`) USING BTREE,
  KEY `edu_study5` (`edu_course_exam_subject_name_id`) USING BTREE,
  KEY `edu_study6` (`edu_campus_school_class_id`) USING BTREE,
  KEY `IDX_CLASS_TIME_START` (`class_time_start`),
  KEY `IDX_CLASS_TIME_END` (`class_time_end`),
  KEY `edu_study_ibfk_6` (`update_admin_user_id`),
  CONSTRAINT `edu_study_ibfk_1` FOREIGN KEY (`edu_course_exam_subject_name_id`) REFERENCES `edu_course_exam_subject_name` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_study_ibfk_2` FOREIGN KEY (`edu_class_type_id`) REFERENCES `edu_class_type` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_study_ibfk_3` FOREIGN KEY (`edu_admin_user_id`) REFERENCES `admin_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_study_ibfk_4` FOREIGN KEY (`admin_user_id`) REFERENCES `admin_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_study_ibfk_5` FOREIGN KEY (`edu_campus_school_class_id`) REFERENCES `edu_campus_school_class` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_study_ibfk_6` FOREIGN KEY (`update_admin_user_id`) REFERENCES `admin_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=423445 DEFAULT CHARSET=utf8mb4 COMMENT='排课表'