CREATE TABLE `edu_student_info` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT,
  `edu_student_id` bigint(11) NOT NULL COMMENT '学生ID',
  `edu_student_number` varchar(255) DEFAULT NULL COMMENT '学号',
  `nationality` varchar(255) DEFAULT NULL COMMENT '国籍',
  `birthplace` varchar(255) DEFAULT NULL COMMENT '出生地',
  `nation` varchar(255) DEFAULT NULL COMMENT '民族',
  `educational` varchar(255) DEFAULT NULL COMMENT '学制',
  `category` int(11) DEFAULT NULL COMMENT '入学类别 1 正常 2转学',
  `university` varchar(255) DEFAULT NULL COMMENT '毕业院校',
  `enrollment_year` bigint(11) DEFAULT NULL COMMENT '入学年份（时间戳）',
  `date_admission` bigint(11) DEFAULT NULL COMMENT '入校日期时间戳）',
  `place` varchar(255) DEFAULT NULL COMMENT '籍贯',
  `residence_address` varchar(1024) DEFAULT NULL COMMENT '户籍地址',
  `address` varchar(1024) DEFAULT NULL COMMENT '居住地址',
  `meal_type` varchar(255) DEFAULT NULL COMMENT '餐费类型',
  `accommodation` int(11) DEFAULT NULL COMMENT '是否住宿 1是 2否',
  `school_bus` int(11) DEFAULT NULL COMMENT '是否乘坐校车 1是 2否',
  `cardholder` varchar(255) DEFAULT NULL COMMENT '持卡人',
  `bank_card_number` varchar(255) DEFAULT NULL COMMENT '银行卡号',
  `bank_name` varchar(255) DEFAULT NULL COMMENT '银行名称',
  `hobby` varchar(1024) DEFAULT NULL COMMENT '爱好',
  `awards` varchar(1024) DEFAULT NULL COMMENT '获奖情况',
  `health` varchar(1024) DEFAULT NULL COMMENT '健康信息',
  `special_constitution` varchar(1024) DEFAULT NULL COMMENT '是否特异体质',
  `recruitment_admin_user_id` int(11) DEFAULT NULL COMMENT '招生办联系人',
  `remarks` varchar(1024) DEFAULT NULL COMMENT '备注',
  `created_time` bigint(11) NOT NULL,
  `update_time` bigint(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `edu_student_info_wj_1` (`edu_student_id`) USING BTREE,
  KEY `edu_student_info_wj_2` (`recruitment_admin_user_id`),
  CONSTRAINT `edu_student_info_ibfk_1` FOREIGN KEY (`edu_student_id`) REFERENCES `edu_student` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_student_info_wj_2` FOREIGN KEY (`recruitment_admin_user_id`) REFERENCES `admin_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=2391 DEFAULT CHARSET=utf8mb4 COMMENT='学籍信息'