CREATE TABLE `edu_activities` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT,
  `status` int(11) NOT NULL DEFAULT '1' COMMENT '课程状态1初始化2已结课',
  `type` int(11) NOT NULL COMMENT '课程类型1线下课2网课3活动4classin网课',
  `activity_type` int(11) NOT NULL COMMENT '活动类型1自习2大考3测验',
  `class_time_start` bigint(11) NOT NULL COMMENT '活动开始时间（时间戳）',
  `class_time_end` bigint(11) NOT NULL COMMENT '活动结束时间（时间戳）',
  `is_position` int(11) NOT NULL COMMENT '位置1 校内 2校外',
  `edu_campus_school_class_id` bigint(11) DEFAULT NULL COMMENT '教室ID',
  `address` varchar(1024) DEFAULT NULL COMMENT '校外地址',
  `edu_course_exam_subject_name_id` bigint(11) DEFAULT NULL COMMENT '科目名称ID',
  `edu_admin_user_id` int(11) DEFAULT NULL COMMENT '负责人',
  `admin_user_id` int(11) NOT NULL COMMENT '操作人',
  `created_time` bigint(11) NOT NULL,
  `update_time` bigint(11) DEFAULT NULL,
  `del` bigint(11) NOT NULL DEFAULT '0',
  `is_send` tinyint(1) DEFAULT '0' COMMENT '是否发送 0-未发送 1-已发送',
  PRIMARY KEY (`id`),
  KEY `edu_activities_1` (`edu_campus_school_class_id`) USING BTREE,
  KEY `edu_activities_2` (`edu_course_exam_subject_name_id`) USING BTREE,
  KEY `edu_activities_3` (`edu_admin_user_id`) USING BTREE,
  KEY `edu_activities_4` (`admin_user_id`) USING BTREE,
  KEY `idx_activity_type_del` (`activity_type`,`del`,`id`),
  CONSTRAINT `edu_activities_ibfk_1` FOREIGN KEY (`edu_campus_school_class_id`) REFERENCES `edu_campus_school_class` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_activities_ibfk_2` FOREIGN KEY (`edu_course_exam_subject_name_id`) REFERENCES `edu_course_exam_subject_name` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_activities_ibfk_3` FOREIGN KEY (`edu_admin_user_id`) REFERENCES `admin_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_activities_ibfk_4` FOREIGN KEY (`admin_user_id`) REFERENCES `admin_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=14959 DEFAULT CHARSET=utf8mb4 COMMENT='课外活动'