CREATE TABLE `edu_teacher` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT,
  `admin_teacher_scheme_id` bigint(11) DEFAULT NULL COMMENT '课耗规则ID',
  `admin_user_id` int(11) NOT NULL COMMENT '后台用户ID',
  `parent_id` bigint(11) DEFAULT NULL COMMENT '上级ID',
  `classin_id` varchar(100) DEFAULT NULL COMMENT 'classinid',
  `name` varchar(255) NOT NULL COMMENT '姓名',
  `nickname` varchar(255) DEFAULT NULL COMMENT '昵称',
  `avatar` varchar(1024) DEFAULT NULL COMMENT '头像',
  `sex` int(11) NOT NULL DEFAULT '3' COMMENT '性别1男2女3其他',
  `job` int(11) DEFAULT '3' COMMENT '工作性质：1全职2兼职3其他',
  `course_style` varchar(1024) DEFAULT NULL COMMENT '授课风格',
  `star` int(11) NOT NULL COMMENT '星级 （数字1-9）',
  `appraise` int(11) NOT NULL DEFAULT '100' COMMENT '老师评分',
  `teacher_introduce` varchar(2048) DEFAULT NULL COMMENT '老师介绍',
  `study_introduce` varchar(2048) DEFAULT NULL COMMENT '留学介绍',
  `remarks` varchar(1024) DEFAULT NULL COMMENT '备注',
  `created_time` bigint(20) NOT NULL,
  `update_time` bigint(20) NOT NULL,
  `del` int(255) NOT NULL DEFAULT '0',
  `rel` int(255) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `edu_teacher1` (`admin_user_id`) USING BTREE,
  KEY `edu_teacher2` (`admin_teacher_scheme_id`) USING BTREE,
  CONSTRAINT `edu_teacher_ibfk_1` FOREIGN KEY (`admin_user_id`) REFERENCES `admin_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_teacher_ibfk_2` FOREIGN KEY (`admin_teacher_scheme_id`) REFERENCES `admin_teacher_scheme` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=2574 DEFAULT CHARSET=utf8mb4 COMMENT='老师'