CREATE TABLE `edu_room_study` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT,
  `type` int(11) NOT NULL DEFAULT '1' COMMENT '课程类型1线下课2网课3活动4classin网课',
  `class_time_start` bigint(11) NOT NULL COMMENT '上课开始时间（时间戳）',
  `class_hour` decimal(4,2) NOT NULL COMMENT '课时数',
  `edu_campus_school_class_id` bigint(11) DEFAULT NULL COMMENT '教室ID',
  `edu_course_exam_subject_name_id` bigint(11) NOT NULL COMMENT '科目名称ID',
  `edu_class_type_id` bigint(11) DEFAULT NULL COMMENT '班级类型ID',
  `edu_admin_user_id` int(11) NOT NULL COMMENT '上课老师ID',
  `admin_user_id` int(11) NOT NULL COMMENT '操作人ID',
  `english_teaching` varchar(255) NOT NULL DEFAULT '1' COMMENT '是否英语授课1不是2是',
  `is_video` int(11) NOT NULL DEFAULT '0' COMMENT '是否录课0不录课 1录课',
  `edu_room_id` bigint(11) NOT NULL COMMENT '排课班级维度—班级ID',
  `edu_study_id` bigint(11) DEFAULT NULL COMMENT '排课ID',
  `is_sync` int(11) NOT NULL DEFAULT '1' COMMENT '同步状态：1-未同步  2-已同步 3-异常',
  `created_time` bigint(11) NOT NULL COMMENT '创建时间（时间戳）',
  `update_time` bigint(11) NOT NULL COMMENT '更新时间（时间戳）',
  `del` int(11) NOT NULL DEFAULT '0' COMMENT '0正常1删除',
  `remarks` varchar(1024) DEFAULT '' COMMENT '异常原因',
  `jingsai_teaching` int(11) NOT NULL DEFAULT '1' COMMENT '是否竞赛 1不是 2是',
  `trial_teaching` int(11) NOT NULL DEFAULT '1' COMMENT '是否是试听课:1不是，2是',
  PRIMARY KEY (`id`),
  KEY `edu_room_study_wj_1` (`edu_course_exam_subject_name_id`) USING BTREE,
  KEY `edu_room_study_wj_2` (`edu_class_type_id`) USING BTREE,
  KEY `edu_room_study_wj_3` (`edu_admin_user_id`) USING BTREE,
  KEY `edu_room_study_wj_4` (`admin_user_id`) USING BTREE,
  KEY `edu_room_study_wj_5` (`edu_campus_school_class_id`) USING BTREE,
  KEY `edu_room_study_wj_6` (`edu_room_id`) USING BTREE,
  KEY `edu_room_study_wj_7` (`edu_study_id`) USING BTREE,
  CONSTRAINT `edu_room_study_ibfk_1` FOREIGN KEY (`edu_course_exam_subject_name_id`) REFERENCES `edu_course_exam_subject_name` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_room_study_ibfk_2` FOREIGN KEY (`edu_class_type_id`) REFERENCES `edu_class_type` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_room_study_ibfk_3` FOREIGN KEY (`edu_admin_user_id`) REFERENCES `admin_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_room_study_ibfk_4` FOREIGN KEY (`admin_user_id`) REFERENCES `admin_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_room_study_ibfk_5` FOREIGN KEY (`edu_campus_school_class_id`) REFERENCES `edu_campus_school_class` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_room_study_ibfk_6` FOREIGN KEY (`edu_room_id`) REFERENCES `edu_room` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_room_study_ibfk_7` FOREIGN KEY (`edu_study_id`) REFERENCES `edu_study` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1634 DEFAULT CHARSET=utf8mb4 COMMENT='班级-班级排课记录表'