CREATE TABLE `edu_achievement_collect_task` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL COMMENT '任务名称',
  `status` int(11) NOT NULL DEFAULT '0' COMMENT '状态  默认0（未生成），1：生成中，2：已生成, 3: 已取消,4:异常',
  `class_time_start` bigint(11) NOT NULL COMMENT '上课开始时间',
  `class_time_end` bigint(11) NOT NULL COMMENT '上课结束时间',
  `class_hours` varchar(128) NOT NULL COMMENT '课时数',
  `test_time` bigint(11) NOT NULL COMMENT '考试时间',
  `task_start_time` bigint(11) DEFAULT NULL COMMENT '任务启动时间',
  `task_finished_time` bigint(11) DEFAULT NULL COMMENT '任务完成时间',
  `admin_user_id` int(11) NOT NULL COMMENT '创建人',
  `update_admin_user_id` int(11) DEFAULT NULL COMMENT '更新人',
  `created_time` bigint(11) NOT NULL COMMENT '创建时间',
  `update_time` bigint(11) DEFAULT NULL COMMENT '更新时间',
  `err_msg` varchar(1024) DEFAULT NULL COMMENT '异常信息',
  `del` bigint(11) NOT NULL DEFAULT '0' COMMENT '是否删除0正常 1删除',
  `exams_year_season_id` bigint(11) DEFAULT NULL COMMENT '年度报考-考试季ID',
  `edu_course_exam_subject_name_ids` varchar(1024) DEFAULT NULL COMMENT '科目名称(四级)ID数组',
  PRIMARY KEY (`id`),
  KEY `edu_achievement_collect_task_sy_1` (`admin_user_id`),
  KEY `edu_achievement_collect_task_sy_2` (`update_admin_user_id`),
  KEY `edu_achievement_collect_task_sy_3` (`exams_year_season_id`),
  CONSTRAINT `edu_achievement_collect_task_wj_1` FOREIGN KEY (`admin_user_id`) REFERENCES `admin_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_achievement_collect_task_wj_2` FOREIGN KEY (`update_admin_user_id`) REFERENCES `admin_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `edu_achievement_collect_task_wj_3` FOREIGN KEY (`exams_year_season_id`) REFERENCES `exams_year_season` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=2204 DEFAULT CHARSET=utf8mb4 COMMENT='测试成绩-分数采集任务表'