CREATE TABLE `edu_teacher_feedback` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID主键',
  `status` tinyint(4) NOT NULL DEFAULT '1' COMMENT '反馈状态1草稿2已发送3已反馈4驳回',
  `study_id` bigint(20) DEFAULT NULL COMMENT '学通排课ID edu_study_id',
  `subject_name_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '科目id',
  `course_time_start` bigint(20) DEFAULT NULL COMMENT '授课开始时间（时间戳）',
  `course_time_end` bigint(20) DEFAULT NULL COMMENT '授课结束时间（时间戳）',
  `course_number` int(11) DEFAULT '0' COMMENT '课程次数',
  `student_id` bigint(20) DEFAULT NULL COMMENT '学生ID',
  `student_ids` varchar(500) NOT NULL DEFAULT '' COMMENT '须填写反馈，学生ids',
  `admin_user_id` bigint(20) NOT NULL COMMENT '创建人老师ID',
  `teacher_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '老师ID',
  `kq_study_id` bigint(20) DEFAULT NULL COMMENT '科桥课程ID ',
  `course_name` varchar(1024) DEFAULT NULL COMMENT '课程名称',
  `school_id` bigint(20) DEFAULT NULL COMMENT '校区id',
  `course_type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '课程类型：1-新课，2-复习课',
  `course_progress` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT '课程进度',
  `review_progress` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT '复习课进度',
  `homework` varchar(500) NOT NULL DEFAULT '' COMMENT '课程作业',
  `last_homework_status` tinyint(4) DEFAULT NULL COMMENT '上次完成作业情况： 1-已完成，2-部分完成，3-完全没做，4-首课无上次作业',
  `last_homework_progress` varchar(500) NOT NULL DEFAULT '' COMMENT '作业完成进度',
  `last_homework_accuracy` varchar(500) NOT NULL DEFAULT '' COMMENT '作业正确率',
  `attendance` tinyint(4) DEFAULT NULL COMMENT '出勤：1-正常上课，2-迟到，3-早退，4-旷课',
  `focus` varchar(100) NOT NULL DEFAULT '' COMMENT '学习专注：1-高效专注，2-认真听讲，3-积极主动，4-渐入佳境，5-缺乏主动，6-投入不足，7-走神敷衍',
  `interaction` varchar(100) NOT NULL DEFAULT '' COMMENT '学习互动：1-互动活跃，2-踊跃发言，3-积极应答，4-尝试互动，5-应答缓慢，6-沉默寡言，7-不敢表达',
  `ability` varchar(100) NOT NULL DEFAULT '' COMMENT '学习能力：1-举一反三，2-触类旁通，3-快速理解，4-尝试拓展，5-有所领悟，6-理解困难，7-不善总结',
  `comprehensive_evaluation` tinyint(4) NOT NULL DEFAULT '0' COMMENT '课堂综合表现，五星评价',
  `summary` text COMMENT '课程总结',
  `type` tinyint(4) NOT NULL DEFAULT '2' COMMENT '数据类型：1-老数据，2-新数据',
  `homework_status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '作业布置状态：0-未布置，1-已布置（班主任），2-已布置，3-已反馈',
  `assign_status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '分配状态',
  `deleted` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否删除 0 未删除 1 删除 默认是0',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间，默认当前时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间，默认当前时间',
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_update_time` (`update_time`),
  KEY `idx_student_id` (`student_id`),
  KEY `idx_study_id` (`study_id`),
  KEY `idx_study_deleted` (`study_id`,`deleted`),
  KEY `idx_created_deleted` (`create_time`,`deleted`),
  KEY `idx_admin_user_id` (`admin_user_id`),
  KEY `idx_userId_startTime` (`admin_user_id`,`course_time_start`),
  KEY `idx_studentIds` (`student_ids`(100)),
  KEY `idx_course_time_start` (`course_time_start`),
  KEY `idx_subject_deleted` (`subject_name_id`,`deleted`),
  KEY `idx_subject_study` (`subject_name_id`,`study_id`)
) ENGINE=InnoDB AUTO_INCREMENT=58511 DEFAULT CHARSET=utf8mb4 COMMENT='老师反馈（新）'