CREATE TABLE `effective_customers` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `campus_value` varchar(100) DEFAULT NULL COMMENT '线索归属校区',
  `now_month` varchar(20) NOT NULL COMMENT '年月',
  `now_date` varchar(20) NOT NULL COMMENT '日期',
  `customer_name` varchar(50) DEFAULT NULL COMMENT '线索姓名',
  `customer_code` varchar(50) DEFAULT NULL COMMENT '线索编码',
  `repeat_type` tinyint(4) NOT NULL COMMENT '线索入库重复类型',
  `customer_create_time` datetime NOT NULL COMMENT '线索创建时间',
  `customer_create_by` int(11) NOT NULL COMMENT '线索创建人',
  `judgment_value` tinyint(4) DEFAULT NULL COMMENT '线索判定',
  `tmk_judgment_value` tinyint(4) DEFAULT NULL COMMENT 'tmk线索判定',
  `level1_channel_code` int(11) NOT NULL COMMENT '一级渠道编码',
  `level1_channel_name` varchar(50) NOT NULL COMMENT '一级渠道名称',
  `level2_channel_code` int(11) NOT NULL COMMENT '二级渠道编码',
  `level2_channel_name` varchar(50) NOT NULL COMMENT '二级渠道名称',
  `level3_channel_code` int(11) DEFAULT NULL COMMENT '三级渠道编码',
  `level3_channel_name` varchar(50) DEFAULT NULL COMMENT '三级渠道名称',
  `level4_channel_code` int(11) DEFAULT NULL COMMENT '四级渠道编码',
  `level4_channel_name` varchar(50) DEFAULT NULL COMMENT '四级渠道名称',
  `sale_user_id` int(11) DEFAULT NULL COMMENT '当前线索销售ID',
  `charge_person_id` int(11) DEFAULT NULL COMMENT '当前负责人ID',
  `first_create_by` int(11) DEFAULT NULL COMMENT '线索首次创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',
  `delete_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否删除  0否 1是',
  `customer_action` tinyint(4) DEFAULT NULL COMMENT '客户动作',
  `customer_source` int(11) DEFAULT NULL COMMENT '线索来源',
  `business_status` varchar(10) DEFAULT NULL COMMENT '   线索业务状态(A/B/C/D)',
  `customer_status` int(11) DEFAULT NULL COMMENT '线索小状态',
  `clue_flag` tinyint(4) DEFAULT NULL COMMENT '是否名单线索   0-否   1-是',
  `channel_name` varchar(255) DEFAULT NULL COMMENT '运营渠道/渠道名称',
  `carrier` varchar(255) DEFAULT NULL COMMENT '载体',
  `keyword` varchar(255) DEFAULT NULL COMMENT '关键字',
  `introduce_user` varchar(100) DEFAULT NULL COMMENT '转介绍人',
  `remaining_recall_time` datetime DEFAULT NULL COMMENT '顾问抽回时间',
  `current_process` tinyint(4) DEFAULT NULL COMMENT '当前进展',
  `last_repeat_type` tinyint(4) DEFAULT NULL COMMENT '最新线索重复类型:   0-新线索   1-有效重复   2-无效重复',
  `sale_flag` tinyint(4) DEFAULT NULL COMMENT '是否下发过顾问   0-未下发过   1-下发过',
  `repeat_customer_time` datetime DEFAULT NULL COMMENT '重复信息时间',
  `last_public_pool_time` datetime DEFAULT NULL COMMENT '最新置入公海时间',
  `special_channel` tinyint(4) DEFAULT NULL COMMENT '特殊渠道   0:默认   1:渠道精推-个人渠道   2:渠道精推-机构渠道   3:渠道数据-个人渠道   4:渠道数据-机构渠道',
  `next_follow_up_time` datetime DEFAULT NULL COMMENT '最新跟进记录的下次跟进时间',
  `last_assign_sale_time` datetime DEFAULT NULL COMMENT '最新分配顾问时间',
  `before_charge_person_id` int(11) DEFAULT NULL COMMENT '前负责人',
  `sale_last_follow_up_time` datetime DEFAULT NULL COMMENT '顾问最新跟进时间',
  `sale_customer_action` tinyint(4) DEFAULT NULL COMMENT '销售客户动作',
  `first_assign_sale_time` datetime DEFAULT NULL COMMENT '首次下发顾问时间',
  `first_confirm_time` datetime DEFAULT NULL COMMENT '首次确认时间',
  `first_follow_up_time` datetime DEFAULT NULL COMMENT '首次跟进时间',
  `create_by_dept_id` int(11) DEFAULT NULL COMMENT '录入人所在部门ID',
  `sale_judgment_value_reason` varchar(255) DEFAULT NULL COMMENT '销售线索判定原因',
  `sale_judgment_value` tinyint(4) DEFAULT NULL COMMENT '销售线索判定',
  `clue_flag_transform_time` datetime DEFAULT NULL COMMENT '转线索时间',
  `sale_judgment_value_user_id` int(11) DEFAULT NULL COMMENT '有效线索判定销售 id',
  PRIMARY KEY (`id`),
  KEY `idx_now_date` (`now_date`),
  KEY `idx_charge_person_id` (`charge_person_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3644236 DEFAULT CHARSET=utf8mb4 COMMENT='销售有效数据记录（线索）'