CREATE TABLE `exams_year_season` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT,
  `cms_article_id` bigint(11) NOT NULL DEFAULT '1' COMMENT '媒体ID',
  `name` varchar(255) NOT NULL COMMENT '考试季名称',
  `exams_year_type_id` bigint(11) NOT NULL COMMENT '考试分类ID',
  `exams_year_quarter_id` bigint(11) DEFAULT NULL COMMENT '季度ID',
  `platform` int(11) NOT NULL COMMENT '发布平台1学通2科桥',
  `entry1_deadline_end` bigint(11) NOT NULL COMMENT '第一阶段结束时间',
  `entry2_deadline_end` bigint(11) NOT NULL COMMENT '第二阶段结束时间',
  `entry3_deadline_end` bigint(11) NOT NULL COMMENT '第三阶段结束时间',
  `created_time` bigint(11) NOT NULL,
  `update_time` bigint(11) DEFAULT NULL,
  `rel` int(11) NOT NULL DEFAULT '0' COMMENT '是否发布0未发布 1已发布',
  `del` int(11) NOT NULL DEFAULT '0',
  `isredo` int(11) NOT NULL DEFAULT '0' COMMENT '是否可以重复考试：0：不可以，1：可以',
  `exams_year_season_type_id` int(11) DEFAULT NULL COMMENT '考试类型ID',
  `admin_category_id` int(11) DEFAULT '3' COMMENT '商户号对应收款主体id（默认科桥）',
  PRIMARY KEY (`id`),
  KEY `exam_year_season1` (`cms_article_id`) USING BTREE,
  KEY `exam_year_season2` (`exams_year_type_id`) USING BTREE,
  KEY `exam_year_season3` (`exams_year_quarter_id`) USING BTREE,
  KEY `exams_year_season_sy_1` (`exams_year_season_type_id`),
  KEY `idx_exams_year_season_platform` (`platform`,`created_time`),
  CONSTRAINT `exams_year_season_ibfk_1` FOREIGN KEY (`cms_article_id`) REFERENCES `cms_article` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `exams_year_season_ibfk_2` FOREIGN KEY (`exams_year_type_id`) REFERENCES `exams_year_type` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `exams_year_season_ibfk_3` FOREIGN KEY (`exams_year_quarter_id`) REFERENCES `exams_year_quarter` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `exams_year_season_wj_1` FOREIGN KEY (`exams_year_season_type_id`) REFERENCES `exams_year_season_type` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=7881 DEFAULT CHARSET=utf8mb4 COMMENT='年度报考-考试季'