CREATE TABLE `exams_year_apply_info` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT,
  `order_list_id` bigint(11) DEFAULT NULL COMMENT '已支付的订单ID',
  `exams_year_season_id` bigint(11) NOT NULL COMMENT '考试季ID',
  `edu_student_id` bigint(11) NOT NULL COMMENT '学生ID',
  `my_user_id` bigint(11) DEFAULT NULL COMMENT '用户ID',
  `exams_year_season_goods_id` bigint(11) NOT NULL COMMENT '商品ID',
  `goods_list_id` bigint(11) DEFAULT NULL COMMENT '考试季商品ID',
  `make_achievement_value` varchar(255) DEFAULT NULL COMMENT '考试组合信息',
  `center_code_value` varchar(255) DEFAULT NULL COMMENT '考试中心代码',
  `seconded_info_value` varchar(255) DEFAULT NULL COMMENT '附议信息内容',
  `ticket_value` varchar(255) DEFAULT NULL COMMENT '准考证号',
  `autograph` varchar(400) DEFAULT NULL COMMENT '签名地址',
  `apply_type` int(1) DEFAULT '0' COMMENT '报名方式：0：用户录入，1：老师录入',
  `admin_user_id` bigint(11) DEFAULT NULL COMMENT '操作人，添加或编辑',
  `created_time` bigint(11) NOT NULL,
  `update_time` bigint(11) DEFAULT NULL,
  `del` int(1) NOT NULL DEFAULT '0' COMMENT '0：未删除，1：已删除',
  PRIMARY KEY (`id`),
  KEY `exams_year_apply_info1` (`order_list_id`) USING BTREE,
  KEY `exams_year_apply_info2` (`exams_year_season_id`) USING BTREE,
  KEY `exams_year_apply_info3` (`edu_student_id`) USING BTREE,
  KEY `exams_year_apply_info4` (`my_user_id`) USING BTREE,
  KEY `exams_year_apply_info5` (`goods_list_id`) USING BTREE,
  KEY `exams_year_apply_info6` (`exams_year_season_goods_id`) USING BTREE,
  KEY `idx_apply_info_composite` (`exams_year_season_id`,`edu_student_id`,`del`),
  CONSTRAINT `exams_year_apply_info_ibfk_1` FOREIGN KEY (`order_list_id`) REFERENCES `order_list` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `exams_year_apply_info_ibfk_2` FOREIGN KEY (`exams_year_season_id`) REFERENCES `exams_year_season` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `exams_year_apply_info_ibfk_3` FOREIGN KEY (`edu_student_id`) REFERENCES `edu_student` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `exams_year_apply_info_ibfk_4` FOREIGN KEY (`my_user_id`) REFERENCES `my_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `exams_year_apply_info_ibfk_5` FOREIGN KEY (`goods_list_id`) REFERENCES `goods_list` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `exams_year_apply_info_ibfk_6` FOREIGN KEY (`exams_year_season_goods_id`) REFERENCES `exams_year_season_goods` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=508 DEFAULT CHARSET=utf8mb4 COMMENT='年度报考-学生报考信息'