CREATE TABLE `exams_year_season_goods` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT,
  `exams_year_season_id` bigint(20) NOT NULL COMMENT '考试季ID',
  `code_name` varchar(255) NOT NULL COMMENT '编码名称',
  `entry1_goods_list_id` bigint(11) NOT NULL COMMENT '第一阶段商品ID',
  `entry2_goods_list_id` bigint(11) NOT NULL COMMENT '第二阶段商品ID',
  `entry3_goods_list_id` bigint(11) NOT NULL COMMENT '第三阶段商品ID',
  `grade` varchar(255) DEFAULT NULL COMMENT '年级',
  `subject_name` varchar(255) NOT NULL COMMENT '科目名称',
  `make_achievement` int(11) NOT NULL DEFAULT '1' COMMENT '是否组合成绩1不组合 2 组合',
  `make_achievement_1` varchar(255) DEFAULT NULL COMMENT '是否组合成绩 - 选项1',
  `make_achievement_2` varchar(255) DEFAULT NULL COMMENT '是否组合成绩 - 选项2',
  `center_code` int(11) NOT NULL DEFAULT '1' COMMENT '是否显示考试中心代码 1不显示 2显示',
  `center_code_content` varchar(1024) DEFAULT NULL COMMENT '是否显示考试中心代码 提示语',
  `ticket` int(11) NOT NULL DEFAULT '1' COMMENT '是否显示准考证 1不显示 2显示',
  `ticket_content` varchar(1024) DEFAULT NULL COMMENT '是否显示准考证 提示语',
  `seconded_info` int(11) NOT NULL DEFAULT '1' COMMENT '是否显示附议信息1不显示 2 显示',
  `seconded_info_content` varchar(1024) DEFAULT NULL COMMENT '是否显示附议信息 提示语',
  `admin_user_id` int(11) NOT NULL COMMENT '操作人',
  `created_time` bigint(11) NOT NULL,
  `update_time` bigint(11) DEFAULT NULL,
  `rel` int(11) NOT NULL DEFAULT '0' COMMENT '是否发布0未发布 1已发布',
  `del` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `exams_year_season_goods1` (`entry1_goods_list_id`) USING BTREE,
  KEY `exams_year_season_goods2` (`entry2_goods_list_id`) USING BTREE,
  KEY `exams_year_season_goods3` (`entry3_goods_list_id`) USING BTREE,
  KEY `exams_year_season_goods4` (`admin_user_id`) USING BTREE,
  KEY `exams_year_season_goods5` (`exams_year_season_id`) USING BTREE,
  CONSTRAINT `exams_year_season_goods_ibfk_1` FOREIGN KEY (`entry1_goods_list_id`) REFERENCES `goods_list` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `exams_year_season_goods_ibfk_2` FOREIGN KEY (`entry2_goods_list_id`) REFERENCES `goods_list` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `exams_year_season_goods_ibfk_3` FOREIGN KEY (`entry3_goods_list_id`) REFERENCES `goods_list` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `exams_year_season_goods_ibfk_4` FOREIGN KEY (`admin_user_id`) REFERENCES `admin_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `exams_year_season_goods_ibfk_5` FOREIGN KEY (`exams_year_season_id`) REFERENCES `exams_year_season` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=66849 DEFAULT CHARSET=utf8mb4 COMMENT='年度报考-商品列表'