CREATE TABLE `keqiao_class` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT,
  `keqiao_class_type_id` int(11) NOT NULL COMMENT '班级类型ID',
  `keqiao_class_category_id` int(11) DEFAULT NULL COMMENT '班级类别ID',
  `edu_campus_school_id` bigint(11) NOT NULL COMMENT '所属校区分校ID',
  `edu_course_exam_subject_id` bigint(11) DEFAULT NULL COMMENT '科目ID edu_course_exam_subject',
  `edu_level_mapping_id` bigint(11) DEFAULT NULL COMMENT '等级映射规则ID',
  `start_school_year` bigint(11) DEFAULT NULL COMMENT '入学年份',
  `end_school_year` bigint(11) DEFAULT NULL COMMENT '毕业年份',
  `name` varchar(255) NOT NULL COMMENT '班级中文名称',
  `num` int(11) DEFAULT NULL COMMENT '计划人数',
  `content` varchar(1024) DEFAULT NULL COMMENT '描述内容',
  `admin_user_id` int(11) NOT NULL COMMENT '操作人',
  `is_stop_class` int(11) NOT NULL DEFAULT '1' COMMENT '是否结班1 正常 2结班',
  `created_time` bigint(11) NOT NULL,
  `update_time` bigint(11) DEFAULT NULL,
  `del` int(11) NOT NULL DEFAULT '0',
  `edu_course_exam_subject_name_id` bigint(11) DEFAULT NULL COMMENT '四级科目ID edu_course_exam_subject_name',
  PRIMARY KEY (`id`),
  KEY `keqiao_class_sy_1` (`keqiao_class_type_id`) USING BTREE,
  KEY `keqiao_class_wj_2` (`edu_campus_school_id`) USING BTREE,
  KEY `keqiao_class_wj_3` (`admin_user_id`) USING BTREE,
  KEY `keqiao_class_wj_4` (`keqiao_class_category_id`) USING BTREE,
  KEY `keqiao_class_wj_5` (`edu_course_exam_subject_id`) USING BTREE,
  KEY `keqiao_class_wj_6` (`edu_level_mapping_id`) USING BTREE,
  CONSTRAINT `keqiao_class_ibfk_1` FOREIGN KEY (`keqiao_class_type_id`) REFERENCES `keqiao_class_type` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `keqiao_class_ibfk_2` FOREIGN KEY (`edu_campus_school_id`) REFERENCES `edu_campus_school` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `keqiao_class_ibfk_3` FOREIGN KEY (`admin_user_id`) REFERENCES `admin_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `keqiao_class_ibfk_4` FOREIGN KEY (`keqiao_class_category_id`) REFERENCES `keqiao_class_category` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `keqiao_class_ibfk_5` FOREIGN KEY (`edu_course_exam_subject_id`) REFERENCES `edu_course_exam_subject` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `keqiao_class_ibfk_6` FOREIGN KEY (`edu_level_mapping_id`) REFERENCES `edu_level_mapping` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=472 DEFAULT CHARSET=utf8mb4 COMMENT='班级'