CREATE TABLE `keqiao_preschool_examination` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `order_list_id` bigint(11) DEFAULT NULL COMMENT '已支付的订单ID',
  `my_user_id` bigint(11) NOT NULL COMMENT '用户ID',
  `student_name` varchar(128) NOT NULL COMMENT '学生姓名',
  `edu_campus_school_id` bigint(11) DEFAULT NULL COMMENT '二级校区id',
  `sex` int(11) NOT NULL DEFAULT '1' COMMENT '性别1男2女',
  `inschool` varchar(255) NOT NULL COMMENT '在读学校',
  `ingrade` varchar(255) NOT NULL COMMENT '在读年级',
  `certificates` varchar(255) DEFAULT NULL COMMENT '身份证号',
  `keqiao_preschool_time_id` bigint(11) NOT NULL COMMENT '考试日期',
  `contacts` varchar(128) NOT NULL COMMENT '联系人',
  `phone` bigint(11) NOT NULL COMMENT '联系方式',
  `address` varchar(255) DEFAULT NULL COMMENT '快递寄送地址',
  `email` varchar(255) DEFAULT NULL COMMENT '电子邮箱',
  `awards` varchar(255) DEFAULT NULL COMMENT '曾获奖励',
  `hobby` varchar(255) DEFAULT NULL COMMENT '获奖情况',
  `advantage_subject` varchar(255) DEFAULT NULL COMMENT '优势科目',
  `url` varchar(500) DEFAULT NULL COMMENT '英语能力证明材料url',
  `abroad` varchar(255) DEFAULT NULL COMMENT '留学意向国家',
  `english_test` varchar(255) DEFAULT NULL COMMENT '是否参加英语考试',
  `form_test` int(11) DEFAULT NULL COMMENT '考试形式1线下2线上',
  `is_admission` int(11) NOT NULL DEFAULT '1' COMMENT '是否生成准考证1未生成 2已生成',
  `test_time` bigint(11) DEFAULT NULL COMMENT '测试时间（时间戳）',
  `created_time` bigint(11) NOT NULL,
  `del` int(11) NOT NULL DEFAULT '0',
  `update_time` bigint(11) DEFAULT NULL,
  `source_type` varchar(255) DEFAULT NULL COMMENT '学校了解来源',
  `math_test_input` int(1) DEFAULT NULL COMMENT '数学卷类型（用户输入）1-中文卷；2-英文卷',
  `org` int(2) NOT NULL DEFAULT '1' COMMENT '学校：0:学通，1科桥，2克勒',
  `present_value` varchar(20) DEFAULT NULL COMMENT '克勒到校人数',
  `cer_type` tinyint(4) NOT NULL DEFAULT '1' COMMENT '证件类型 1:身份证，2：其他',
  `math_test` int(11) DEFAULT NULL COMMENT '数学笔试1-中问卷;2-英文卷',
  `intended_courses` varchar(255) DEFAULT NULL COMMENT '意向课程',
  PRIMARY KEY (`id`),
  KEY `cms_test_registration2` (`my_user_id`) USING BTREE,
  KEY `cms_test_registration3` (`student_name`) USING BTREE,
  KEY `keqiao_preschool_examination_ibfk_4` (`edu_campus_school_id`),
  KEY `idx_order_list_id` (`order_list_id`),
  KEY `idx_keqiao_preschool_time_id` (`keqiao_preschool_time_id`),
  CONSTRAINT `keqiao_preschool_examination_ibfk_2` FOREIGN KEY (`my_user_id`) REFERENCES `my_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `keqiao_preschool_examination_ibfk_4` FOREIGN KEY (`edu_campus_school_id`) REFERENCES `edu_campus_school` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=251 DEFAULT CHARSET=utf8mb4 COMMENT='学前考试报名'