CREATE TABLE `keqiao_study_leave` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT,
  `edu_student_id` bigint(11) NOT NULL COMMENT '学生ID',
  `start_time` bigint(11) NOT NULL COMMENT '开始时间',
  `end_time` bigint(11) NOT NULL COMMENT '结束时间',
  `status` int(11) NOT NULL DEFAULT '1' COMMENT '审批状体1初始化2已通过3已驳回',
  `admin_user_id` int(11) DEFAULT NULL COMMENT '审批人',
  `type` int(11) NOT NULL COMMENT '请假类型1事假 2病假',
  `call_api` int(11) DEFAULT '1' COMMENT '是否外出：2不外出，1外出',
  `door_authorization_status` int(11) NOT NULL DEFAULT '1' COMMENT '门禁授权状态：1.未授权 2.已经授权 3.授权失败',
  `authorization_msg` varchar(2048) DEFAULT NULL COMMENT '授权结果',
  `remarks` varchar(255) DEFAULT NULL COMMENT '备注',
  `created_time` bigint(11) NOT NULL COMMENT '创建时间',
  `update_time` bigint(11) DEFAULT NULL COMMENT '审批时间',
  `del` int(11) NOT NULL DEFAULT '0',
  `my_user_id` bigint(11) DEFAULT NULL COMMENT '请假创建者my_user_id',
  `created_admin_user_id` int(11) DEFAULT NULL COMMENT '班主任请假id(管理员)',
  PRIMARY KEY (`id`),
  KEY `keqiao_study_leave_wj_1` (`edu_student_id`) USING BTREE,
  KEY `keqiao_study_leave_wj_2` (`admin_user_id`) USING BTREE,
  KEY `keqiao_study_leave_ibfk_3_idx` (`my_user_id`),
  KEY `keqiao_study_leave_wj_4` (`created_admin_user_id`),
  CONSTRAINT `keqiao_study_leave_ibfk_1` FOREIGN KEY (`edu_student_id`) REFERENCES `edu_student` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `keqiao_study_leave_ibfk_2` FOREIGN KEY (`admin_user_id`) REFERENCES `admin_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `keqiao_study_leave_ibfk_3` FOREIGN KEY (`my_user_id`) REFERENCES `my_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `keqiao_study_leave_wj_4` FOREIGN KEY (`created_admin_user_id`) REFERENCES `admin_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=403 DEFAULT CHARSET=utf8mb4 COMMENT='排课请假'