CREATE TABLE `keqiao_study` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT,
  `type` int(11) NOT NULL COMMENT '课程类型1线下课程 2网课 3活动4考试',
  `type_kinds` varchar(255) DEFAULT NULL COMMENT '课程类型的种类',
  `keqiao_class_id` bigint(11) DEFAULT NULL COMMENT '班级ID',
  `edu_campus_school_id` bigint(11) NOT NULL COMMENT '所属校区分校ID',
  `edu_course_exam_subject_name_id` bigint(11) DEFAULT NULL COMMENT '科目名称ID',
  `keqiao_time_table_id` bigint(11) DEFAULT NULL COMMENT '作息时间ID',
  `keqiao_time_table_section_id` bigint(11) DEFAULT NULL COMMENT '作息时间课节ID',
  `class_time_start` bigint(11) NOT NULL COMMENT '上课/活动 开始时间（时间戳）',
  `class_time_end` bigint(11) NOT NULL COMMENT '上课/活动 结束时间（时间戳）',
  `name` varchar(255) DEFAULT NULL COMMENT '课程/活动 名称',
  `admin_user_id` int(11) NOT NULL COMMENT '操作人',
  `is_clash` int(11) NOT NULL DEFAULT '1' COMMENT '是否冲突排课 1不冲突  2冲突',
  `edu_campus_school_class_id` bigint(11) DEFAULT NULL COMMENT '教室ID',
  `address` varchar(1024) DEFAULT NULL COMMENT '校外上课地址',
  `remarks` varchar(1024) DEFAULT NULL COMMENT '备注',
  `keqiao_surface_id` bigint(11) DEFAULT NULL COMMENT '课表ID',
  `is_clockin` int(11) NOT NULL DEFAULT '1' COMMENT '是否考勤  1未全部考勤 2全部考勤 3全部考勤缺勤',
  `created_time` bigint(11) NOT NULL,
  `update_time` bigint(11) NOT NULL,
  `del` int(11) NOT NULL DEFAULT '0',
  `org` tinyint(4) NOT NULL DEFAULT '1' COMMENT '1: 科桥; 2: 克勒',
  PRIMARY KEY (`id`),
  KEY `keqiao_class_study_wj_2` (`admin_user_id`) USING BTREE,
  KEY `keqiao_class_study_wj_3` (`edu_course_exam_subject_name_id`) USING BTREE,
  KEY `keqiao_class_study_wj_4` (`edu_campus_school_id`) USING BTREE,
  KEY `keqiao_class_study_wj_6` (`edu_campus_school_class_id`) USING BTREE,
  KEY `keqiao_class_study_wj_7` (`keqiao_time_table_id`) USING BTREE,
  KEY `keqiao_class_study_wj_9` (`keqiao_class_id`) USING BTREE,
  KEY `keqiao_class_study_wj_10` (`keqiao_surface_id`) USING BTREE,
  KEY `keqiao_class_study_wj_11` (`class_time_start`) USING BTREE,
  CONSTRAINT `keqiao_study_ibfk_1` FOREIGN KEY (`keqiao_surface_id`) REFERENCES `keqiao_surface` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `keqiao_study_ibfk_2` FOREIGN KEY (`admin_user_id`) REFERENCES `admin_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `keqiao_study_ibfk_3` FOREIGN KEY (`edu_course_exam_subject_name_id`) REFERENCES `edu_course_exam_subject_name` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `keqiao_study_ibfk_4` FOREIGN KEY (`edu_campus_school_id`) REFERENCES `edu_campus_school` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `keqiao_study_ibfk_5` FOREIGN KEY (`edu_campus_school_class_id`) REFERENCES `edu_campus_school_class` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `keqiao_study_ibfk_6` FOREIGN KEY (`keqiao_time_table_id`) REFERENCES `keqiao_time_table` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=588679 DEFAULT CHARSET=utf8mb4 COMMENT='排课（日程）'