CREATE TABLE `order_student_consume` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT,
  `type` int(11) NOT NULL DEFAULT '1' COMMENT '订单状态1扣款2增款',
  `status` int(11) NOT NULL DEFAULT '1' COMMENT '状态1预扣2实扣',
  `order_student_id` bigint(11) NOT NULL COMMENT '扣款订单ID',
  `edu_study_id` bigint(11) DEFAULT NULL COMMENT '排课ID',
  `edu_student_id` bigint(11) NOT NULL COMMENT '学生ID',
  `edu_student_type_id` bigint(11) DEFAULT NULL COMMENT '学生类型ID',
  `edu_student_type_project_id` bigint(11) DEFAULT NULL COMMENT '报读课程ID',
  `customer_admin_user_id` int(11) DEFAULT NULL COMMENT '该条记录客服',
  `total_amount` bigint(11) NOT NULL COMMENT '标准扣费金额（单位分）',
  `type_amount` bigint(11) NOT NULL COMMENT '系数扣费金额（单位分）',
  `amount` bigint(11) NOT NULL COMMENT '折后扣款金额（单位分）',
  `admin_user_id` int(11) DEFAULT NULL COMMENT '操作人ID',
  `remarks` varchar(1024) DEFAULT NULL COMMENT '备注',
  `created_time` bigint(11) NOT NULL,
  `update_time` bigint(11) NOT NULL,
  `del` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `order_student_consume1` (`order_student_id`) USING BTREE,
  KEY `order_student_consume2` (`edu_study_id`) USING BTREE,
  KEY `order_student_consume3` (`edu_student_id`) USING BTREE,
  KEY `order_student_consume4` (`admin_user_id`) USING BTREE,
  KEY `order_student_consume_wj_5` (`edu_student_type_id`) USING BTREE,
  KEY `order_student_consume_wj_6` (`edu_student_type_project_id`) USING BTREE,
  KEY `order_student_consume_wj_7` (`customer_admin_user_id`) USING BTREE,
  KEY `idx_opt` (`order_student_id`,`del`,`status`,`type`,`amount`),
  CONSTRAINT `order_student_consume_ibfk_1` FOREIGN KEY (`order_student_id`) REFERENCES `order_student` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `order_student_consume_ibfk_2` FOREIGN KEY (`edu_study_id`) REFERENCES `edu_study` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `order_student_consume_ibfk_3` FOREIGN KEY (`edu_student_id`) REFERENCES `edu_student` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `order_student_consume_ibfk_4` FOREIGN KEY (`admin_user_id`) REFERENCES `admin_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `order_student_consume_ibfk_5` FOREIGN KEY (`edu_student_type_id`) REFERENCES `edu_student_type` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `order_student_consume_ibfk_6` FOREIGN KEY (`edu_student_type_project_id`) REFERENCES `edu_student_type_project` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `order_student_consume_ibfk_7` FOREIGN KEY (`customer_admin_user_id`) REFERENCES `admin_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=157193 DEFAULT CHARSET=utf8mb4 COMMENT='订单消耗记录'