CREATE TABLE `order_student_received_settlement` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT,
  `order_student_received_id` bigint(11) NOT NULL COMMENT '回款ID',
  `settlement_amount` bigint(11) DEFAULT NULL COMMENT '实际结算金额',
  `commission_rate` bigint(11) DEFAULT NULL COMMENT '佣金比率（0-10000）例子：10000：100%；200：2%；550：5.50%',
  `payment_time` bigint(11) DEFAULT NULL COMMENT '支付时间（时间戳）',
  `applicant_time` bigint(11) DEFAULT NULL COMMENT '发起申请结算时间（时间戳）',
  `admin_user_channel_id` bigint(11) DEFAULT NULL COMMENT '渠道库ID',
  `collection_name` varchar(255) DEFAULT NULL COMMENT '收款账户名',
  `back_account` varchar(255) DEFAULT NULL COMMENT '银行账号',
  `back_name` varchar(255) DEFAULT NULL COMMENT '开户行',
  `admin_category_id` int(11) DEFAULT NULL COMMENT '公司名称表ID',
  `created_time` bigint(11) NOT NULL COMMENT '创建时间（时间戳）',
  `admin_user_id` int(11) NOT NULL COMMENT '创建人后台用户ID',
  `del` int(11) NOT NULL DEFAULT '0' COMMENT '0-正常；1-删除',
  PRIMARY KEY (`id`),
  KEY `admin_channel_settlement_wj_1` (`order_student_received_id`),
  KEY `admin_channel_settlement_wj_2` (`admin_user_id`),
  KEY `admin_channel_settlement_wj_3_idx` (`admin_user_channel_id`),
  KEY `admin_channel_settlement_sy_1` (`admin_category_id`),
  CONSTRAINT `admin_channel_settlement_wj_1` FOREIGN KEY (`order_student_received_id`) REFERENCES `order_student_received` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `admin_channel_settlement_wj_2` FOREIGN KEY (`admin_user_id`) REFERENCES `admin_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `admin_channel_settlement_wj_3` FOREIGN KEY (`admin_user_channel_id`) REFERENCES `admin_user_channel` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `admin_channel_settlement_wj_4` FOREIGN KEY (`admin_category_id`) REFERENCES `admin_category` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=55 DEFAULT CHARSET=utf8mb4 COMMENT='回款计划-佣金结算表'