CREATE TABLE `order_student_refund` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT,
  `order_student_id` bigint(11) NOT NULL COMMENT '订单ID',
  `type` int(11) NOT NULL COMMENT '类型1转课/升级 2退款',
  `status` int(11) NOT NULL DEFAULT '1' COMMENT '状态1审核中 2已通过3驳回',
  `upgrade_amount` bigint(11) NOT NULL COMMENT '转课或升级金额（精确到分）',
  `refund_amount` bigint(11) NOT NULL COMMENT '退款金额（精确到分）',
  `launch_admin_user_id` int(11) NOT NULL COMMENT '退款发起人ID',
  `confirm_admin_user_id` int(11) DEFAULT NULL COMMENT '订单审批人ID',
  `refund_time` bigint(11) DEFAULT NULL COMMENT '退款日期',
  `remarks` varchar(1024) DEFAULT NULL COMMENT '备注',
  `created_time` bigint(11) NOT NULL COMMENT '创建时间',
  `update_time` bigint(11) DEFAULT NULL COMMENT '最后更新时间',
  `del` int(11) NOT NULL DEFAULT '0' COMMENT '是否删除',
  `payment_status` varchar(256) DEFAULT NULL COMMENT '退款方式',
  `payment_admin_user_id` int(11) DEFAULT NULL COMMENT '操作支付的操作人',
  PRIMARY KEY (`id`),
  KEY `order_student_refund1` (`order_student_id`) USING BTREE,
  KEY `order_student_refund2` (`launch_admin_user_id`) USING BTREE,
  KEY `order_student_refund3` (`confirm_admin_user_id`) USING BTREE,
  KEY `order_student_refund_ibfk_4` (`payment_admin_user_id`),
  CONSTRAINT `order_student_refund_ibfk_1` FOREIGN KEY (`order_student_id`) REFERENCES `order_student` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `order_student_refund_ibfk_2` FOREIGN KEY (`launch_admin_user_id`) REFERENCES `admin_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `order_student_refund_ibfk_3` FOREIGN KEY (`confirm_admin_user_id`) REFERENCES `admin_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `order_student_refund_ibfk_4` FOREIGN KEY (`payment_admin_user_id`) REFERENCES `admin_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=782 DEFAULT CHARSET=utf8mb4 COMMENT='订单退款记录'