CREATE TABLE `order_list` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '订单id',
  `prepay_id` varchar(128) DEFAULT NULL,
  `transaction_id` varchar(128) DEFAULT NULL COMMENT '微信订单id',
  `refund_id` varchar(128) DEFAULT NULL COMMENT '退款ID',
  `name` varchar(128) NOT NULL COMMENT '订单名称',
  `contacts` varchar(128) NOT NULL COMMENT '联系方式',
  `my_user_id` bigint(11) NOT NULL COMMENT '用户id',
  `cms_article_id` bigint(11) NOT NULL DEFAULT '0' COMMENT '媒体id',
  `goods_id` bigint(11) NOT NULL COMMENT '商品id',
  `type` int(11) NOT NULL DEFAULT '0' COMMENT '订单状态 0 初始化 1 已支付2已退款',
  `deliver_status` int(11) NOT NULL DEFAULT '1' COMMENT '订单发货状态：1.付款未发货 2.付款已发货',
  `order_total` decimal(11,0) NOT NULL COMMENT '订单金额',
  `pay_order_total` decimal(11,0) NOT NULL DEFAULT '0' COMMENT '已付款金额',
  `operator` varchar(128) NOT NULL COMMENT '操作人',
  `time` varchar(128) NOT NULL COMMENT '创建时间',
  `pay_time` varchar(128) DEFAULT NULL COMMENT '支付时间',
  `address` varchar(1024) DEFAULT NULL COMMENT '地址',
  `remarks` varchar(1024) DEFAULT NULL COMMENT '备注',
  `admin_user_id` int(11) DEFAULT NULL COMMENT '退款操作人',
  `express_name` varchar(255) DEFAULT NULL COMMENT '快递名称',
  `express_number` varchar(255) DEFAULT NULL COMMENT '快递单号',
  `del` int(11) NOT NULL DEFAULT '0',
  `baoming_id` bigint(11) DEFAULT NULL,
  `user_action_set_id` varchar(128) DEFAULT NULL,
  `click_id` varchar(128) DEFAULT NULL,
  `platform` int(11) NOT NULL DEFAULT '1' COMMENT '平台1学通2科桥',
  `admin_pay_order_id` bigint(11) DEFAULT NULL COMMENT '支付单ID',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间,默认当前时间',
  `out_trade_no` varchar(64) DEFAULT NULL COMMENT '商户订单号',
  PRIMARY KEY (`id`),
  KEY `order_list_my_user_id` (`my_user_id`) USING BTREE,
  KEY `order_list_my_user_id1` (`admin_user_id`) USING BTREE,
  KEY `order_list_ibfk_3` (`admin_pay_order_id`),
  KEY `idx_time` (`time`),
  KEY `idx_create_time` (`create_time`),
  CONSTRAINT `order_list_ibfk_1` FOREIGN KEY (`my_user_id`) REFERENCES `my_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `order_list_ibfk_2` FOREIGN KEY (`admin_user_id`) REFERENCES `admin_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `order_list_ibfk_3` FOREIGN KEY (`admin_pay_order_id`) REFERENCES `admin_pay_order` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=10012919 DEFAULT CHARSET=utf8 COMMENT='订单列表'