CREATE TABLE `order_student` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT,
  `main_order_student_id` bigint(11) DEFAULT NULL COMMENT '主订单ID order_student_id（只能有一级）',
  `order_contract_template_id` bigint(20) DEFAULT NULL COMMENT '合同模版ID',
  `status` int(11) NOT NULL DEFAULT '1' COMMENT '状态1审批中2驳回3已通过4已退款5退款中6迁移中',
  `valid` int(11) NOT NULL DEFAULT '0' COMMENT '是否生效0未生效1已生效2已耗尽3转移中',
  `student_id` bigint(11) DEFAULT NULL COMMENT '学生id',
  `edu_student_type_id` bigint(11) DEFAULT NULL COMMENT '学生类型ID',
  `edu_student_type_project_id` bigint(11) DEFAULT NULL COMMENT '报读项目ID',
  `title` varchar(255) DEFAULT NULL COMMENT '订单标题',
  `order_number` varchar(255) DEFAULT NULL COMMENT '订单编号',
  `type_id` int(11) NOT NULL COMMENT '订单类型',
  `signing_date` bigint(11) DEFAULT NULL COMMENT '签约日期（时间戳）',
  `pattern_id` int(11) NOT NULL COMMENT '订单模式order_pattern',
  `region` varchar(255) DEFAULT NULL COMMENT '地区',
  `edu_campus_id` bigint(11) DEFAULT NULL COMMENT '校区ID',
  `order_entry_id` bigint(11) DEFAULT NULL COMMENT '项目名称ID',
  `project_name` varchar(255) DEFAULT NULL COMMENT '项目名称',
  `goods_id` bigint(11) DEFAULT NULL COMMENT '产品ID',
  `products_num` int(11) NOT NULL DEFAULT '1' COMMENT '产品数量',
  `admin_user_id` int(11) NOT NULL COMMENT '订单创建人ID',
  `total_amount` bigint(11) NOT NULL COMMENT '订单总金额（精确到分）',
  `discount` int(11) DEFAULT NULL COMMENT '订单折扣（0.85=8500=85折）',
  `transaction_amount` bigint(11) NOT NULL COMMENT '成交金额（精确到分）',
  `additional` varchar(1024) DEFAULT NULL COMMENT '合同附件（文件地址）',
  `remarks` varchar(1024) DEFAULT NULL COMMENT '备注',
  `supplemental_agreement` varchar(1024) DEFAULT NULL COMMENT '补充协议',
  `created_time` bigint(11) NOT NULL COMMENT '订单创建时间',
  `update_time` bigint(11) NOT NULL COMMENT '最后修改时间',
  `del` int(11) NOT NULL DEFAULT '0' COMMENT '是否删除0正常1删除',
  `education_stage` varchar(255) DEFAULT NULL COMMENT '合同-学历阶段',
  `app_time` varchar(255) DEFAULT NULL COMMENT '合同-申请入学时间',
  `contract_end` varchar(255) DEFAULT NULL COMMENT '合同-合同有效期',
  `colleges_num` varchar(255) DEFAULT NULL COMMENT '合同-院校数',
  `pro_num` varchar(255) DEFAULT NULL COMMENT '合同-专业数',
  `study_abroad` varchar(255) DEFAULT NULL COMMENT '合同-留学国家',
  `ht_total_amount` int(11) DEFAULT NULL COMMENT '合同-总金额',
  `ht_discount` int(11) DEFAULT NULL COMMENT '合同-折扣',
  `ht_transaction_amount` int(11) DEFAULT NULL COMMENT '合同-实际金额',
  `ht_zhuanye` varchar(255) DEFAULT NULL COMMENT '合同-专业',
  `ht_clshijian` varchar(255) DEFAULT NULL COMMENT '合同-入学材料时间',
  `ht_cjsjshijian` varchar(255) DEFAULT NULL COMMENT '合同-成绩上交时间',
  `create_admin_department_children_id` bigint(11) DEFAULT NULL COMMENT '订单创建人所在部门',
  PRIMARY KEY (`id`),
  KEY `order_student1` (`type_id`) USING BTREE,
  KEY `order_student2` (`pattern_id`) USING BTREE,
  KEY `order_student3` (`goods_id`) USING BTREE,
  KEY `order_student4` (`admin_user_id`) USING BTREE,
  KEY `order_student5` (`student_id`) USING BTREE,
  KEY `order_student6` (`order_entry_id`) USING BTREE,
  KEY `order_student7` (`edu_campus_id`) USING BTREE,
  KEY `order_student8` (`order_contract_template_id`) USING BTREE,
  KEY `order_student_wj_9` (`edu_student_type_id`) USING BTREE,
  KEY `order_student_wj_10` (`edu_student_type_project_id`) USING BTREE,
  CONSTRAINT `order_student_ibfk_1` FOREIGN KEY (`type_id`) REFERENCES `order_type` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `order_student_ibfk_10` FOREIGN KEY (`edu_student_type_project_id`) REFERENCES `edu_student_type_project` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `order_student_ibfk_2` FOREIGN KEY (`edu_student_type_id`) REFERENCES `edu_student_type` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `order_student_ibfk_3` FOREIGN KEY (`pattern_id`) REFERENCES `order_pattern` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `order_student_ibfk_4` FOREIGN KEY (`goods_id`) REFERENCES `edu_goods` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `order_student_ibfk_5` FOREIGN KEY (`admin_user_id`) REFERENCES `admin_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `order_student_ibfk_6` FOREIGN KEY (`student_id`) REFERENCES `edu_student` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `order_student_ibfk_7` FOREIGN KEY (`order_entry_id`) REFERENCES `order_entry` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `order_student_ibfk_8` FOREIGN KEY (`edu_campus_id`) REFERENCES `edu_campus` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `order_student_ibfk_9` FOREIGN KEY (`order_contract_template_id`) REFERENCES `order_contract_template` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=6727 DEFAULT CHARSET=utf8mb4 COMMENT='订单'