CREATE TABLE `order_student_received` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT,
  `status` int(11) NOT NULL DEFAULT '1' COMMENT '状态1审批中2驳回3已通过',
  `type` int(11) NOT NULL DEFAULT '1' COMMENT '类型 1回款 2退款',
  `refund_order_student_received_id` bigint(11) DEFAULT NULL COMMENT '当type为2时需要填写',
  `type_id` int(11) DEFAULT NULL COMMENT '回款类型ID 同表order_type',
  `return_order_student_id` bigint(11) DEFAULT NULL COMMENT '回款来源订单ID',
  `order_student_id` bigint(11) NOT NULL COMMENT '学生订单ID',
  `edu_student_type_id` bigint(11) DEFAULT NULL COMMENT '学生类型ID',
  `edu_student_type_project_id` bigint(11) DEFAULT NULL COMMENT '报读项目ID',
  `order_list_id` bigint(11) DEFAULT NULL COMMENT '网站支付订单ID',
  `write_source` int(11) NOT NULL DEFAULT '1' COMMENT '写入来源1 手动创建 2系统自动写入',
  `account_title` varchar(1024) DEFAULT NULL COMMENT '回款账户名称',
  `account_title_id` int(11) DEFAULT NULL COMMENT '回款账户名称ID',
  `collection_date` bigint(11) NOT NULL COMMENT '回款日期',
  `admin_user_id` int(11) NOT NULL COMMENT '回款创建人ID',
  `admin_department_children_id` bigint(11) DEFAULT NULL COMMENT '回款创建人部门ID',
  `remarks` varchar(1024) DEFAULT NULL COMMENT '备注',
  `transfer_remarks` varchar(1024) DEFAULT NULL COMMENT '转实收备注',
  `collection_amount` bigint(11) NOT NULL COMMENT '回款金额（精确到分）',
  `collection_admin_user_id` int(11) NOT NULL COMMENT '收款人ID',
  `collection_admin_department_children_id` bigint(11) DEFAULT NULL COMMENT '收款人所在部门',
  `created_time` bigint(11) NOT NULL COMMENT '回款创建时间',
  `update_time` bigint(11) NOT NULL COMMENT '最后修改时间',
  `del` int(11) NOT NULL DEFAULT '0',
  `settlement_status` int(11) NOT NULL DEFAULT '1' COMMENT '回款的渠道佣金结算状态：1-未申请、2-已申请(审批通过)、3-已结算,4-审批中,5-不结算',
  PRIMARY KEY (`id`),
  KEY `order_student4` (`admin_user_id`) USING BTREE,
  KEY `order_student_received_ibfk_1` (`order_student_id`) USING BTREE,
  KEY `order_student_received_ibfk_2` (`collection_admin_user_id`) USING BTREE,
  KEY `order_student_received_ibfk_4` (`return_order_student_id`) USING BTREE,
  KEY `order_student_received_ibfk_5` (`type_id`) USING BTREE,
  KEY `order_student_received_ibfk_6` (`edu_student_type_id`) USING BTREE,
  KEY `order_student_received_ibfk_7` (`edu_student_type_project_id`) USING BTREE,
  KEY `order_student_received_ibfk_8` (`order_list_id`) USING BTREE,
  KEY `order_student_received_ibfk_9` (`admin_department_children_id`) USING BTREE,
  KEY `order_student_received_ibfk_10` (`collection_admin_department_children_id`),
  KEY `order_student_received_sy_10` (`refund_order_student_received_id`),
  CONSTRAINT `order_student_received_ibfk_1` FOREIGN KEY (`order_student_id`) REFERENCES `order_student` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `order_student_received_ibfk_10` FOREIGN KEY (`collection_admin_department_children_id`) REFERENCES `admin_department_children` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `order_student_received_ibfk_2` FOREIGN KEY (`collection_admin_user_id`) REFERENCES `admin_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `order_student_received_ibfk_3` FOREIGN KEY (`admin_user_id`) REFERENCES `admin_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `order_student_received_ibfk_4` FOREIGN KEY (`return_order_student_id`) REFERENCES `order_student` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `order_student_received_ibfk_5` FOREIGN KEY (`type_id`) REFERENCES `order_type` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `order_student_received_ibfk_6` FOREIGN KEY (`edu_student_type_id`) REFERENCES `edu_student_type` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `order_student_received_ibfk_7` FOREIGN KEY (`edu_student_type_project_id`) REFERENCES `edu_student_type_project` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `order_student_received_ibfk_8` FOREIGN KEY (`order_list_id`) REFERENCES `order_list` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `order_student_received_ibfk_9` FOREIGN KEY (`admin_department_children_id`) REFERENCES `admin_department_children` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `order_student_received_wj_10` FOREIGN KEY (`refund_order_student_received_id`) REFERENCES `order_student_received` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=108528 DEFAULT CHARSET=utf8mb4 COMMENT='回款计划'