CREATE TABLE `study_abroad_planning_info` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '信息ID',
  `planning_info_name` varchar(255) DEFAULT NULL COMMENT '规划信息表名称',
  `order_id` bigint(11) NOT NULL COMMENT '订单ID',
  `clue_number` varchar(255) DEFAULT NULL COMMENT '线索编号',
  `product_name` varchar(255) DEFAULT NULL COMMENT '产品名称',
  `course_consultant_id` bigint(11) NOT NULL COMMENT '课程顾问ID',
  `edu_student_type_id` bigint(11) NOT NULL COMMENT '学员类型ID',
  `collection_amount` bigint(11) DEFAULT NULL COMMENT '回款金额',
  `student_id` bigint(11) NOT NULL COMMENT '学生ID',
  `nationality` varchar(100) DEFAULT NULL COMMENT '国籍',
  `current_school` varchar(128) DEFAULT NULL COMMENT '在读学校',
  `current_grade` int(11) DEFAULT NULL COMMENT '在读年级',
  `phone` varchar(20) DEFAULT NULL COMMENT '手机号',
  `wechat` varchar(100) DEFAULT NULL COMMENT '微信号',
  `study_abroad_country` varchar(255) DEFAULT NULL COMMENT '留学国家 支持多个国家',
  `course_system` int(11) DEFAULT NULL COMMENT '课程体系',
  `target_university` text COMMENT '目标大学',
  `major_direction` text COMMENT '专业方向',
  `application_time` datetime DEFAULT NULL COMMENT '申请时间',
  `course_selection` text COMMENT '选课情况',
  `existing_academics` text COMMENT '已有学业',
  `language_scores` text COMMENT '语言成绩',
  `background_activities` text COMMENT '背提/活动经验',
  `status` int(11) NOT NULL DEFAULT '0' COMMENT '状态 0-未填写 1-已填写 2-已提交 3-已驳回 4-已分配',
  `planner_id` int(11) DEFAULT NULL COMMENT '规划师ID',
  `planner_assign_time` datetime DEFAULT NULL COMMENT '规划师分配时间',
  `service_start_time` datetime DEFAULT NULL COMMENT '服务开始时间',
  `service_end_time` datetime DEFAULT NULL COMMENT '服务结束时间',
  `info_submit_time` datetime DEFAULT NULL COMMENT '信息表提交时间',
  `transfer_teacher_id` bigint(11) DEFAULT NULL COMMENT '转案老师iD',
  `send` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否发送（0表示未发送，1表示已发送）',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `del` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否被删除（0表示未删除，1表示已删除）',
  `application_start_time` datetime DEFAULT NULL COMMENT '申请季开始时间',
  `application_end_time` datetime DEFAULT NULL COMMENT '申请季结束时间',
  `application_level` int(11) DEFAULT NULL COMMENT '申请级别(1中学 2本科 3硕士 4博士 )',
  `plan_status` int(11) NOT NULL DEFAULT '1' COMMENT '当前进度改为：1:规划中 2:申请中 3:结案 4:暂停 5:退费',
  `plan_service_status` int(11) NOT NULL DEFAULT '1' COMMENT '规划服务状态（1申请中， 2规划中）',
  `remark` varchar(1024) DEFAULT NULL COMMENT '备注',
  `study_abroad_major_id` bigint(20) DEFAULT NULL COMMENT '专业方向ID',
  PRIMARY KEY (`id`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_course_consultant_id` (`course_consultant_id`),
  KEY `idx_planner_id` (`planner_id`),
  KEY `idx_status` (`status`),
  KEY `idx_created_time` (`created_time`)
) ENGINE=InnoDB AUTO_INCREMENT=66 DEFAULT CHARSET=utf8mb4 COMMENT='留学规划信息表'