CREATE TABLE `study_abroad_proofread_book` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `student_id` bigint(11) NOT NULL COMMENT '学生ID',
  `application_country` varchar(255) NOT NULL COMMENT '申请国家',
  `application_school` varchar(255) NOT NULL COMMENT '申请学校',
  `application_major` varchar(255) NOT NULL COMMENT '申请专业',
  `course_code` varchar(255) DEFAULT NULL COMMENT '课程代码',
  `course_website_address` varchar(500) DEFAULT NULL COMMENT '课程网址地址',
  `status` int(11) NOT NULL DEFAULT '0' COMMENT '定校状态（0-未定校、1-已定校）',
  `del` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否被删除（0表示未删除，1表示已删除）',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_user_id` bigint(11) NOT NULL COMMENT '操作人',
  `book_time` datetime DEFAULT NULL COMMENT '最新定校时间',
  `customized_school` varchar(255) DEFAULT NULL COMMENT '自定义学校',
  `course_name` varchar(255) DEFAULT NULL COMMENT '课程名称',
  `admission_time` date DEFAULT NULL COMMENT '入学时间 年-月-日',
  `application_deadline` date DEFAULT NULL COMMENT '申请截止时间',
  `qs_ranking` int(11) DEFAULT NULL COMMENT 'QS排名',
  `academic_requirements` varchar(2000) DEFAULT NULL COMMENT '学术要求',
  `language_requirements` varchar(2000) DEFAULT NULL COMMENT '语言要求',
  `written_test_requirements` varchar(2000) DEFAULT NULL COMMENT '笔试要求',
  `study_abroad_major_id` bigint(20) DEFAULT NULL COMMENT '专业方向ID',
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_update_time` (`update_time`)
) ENGINE=InnoDB AUTO_INCREMENT=260 DEFAULT CHARSET=utf8mb4 COMMENT='留学定校书'