CREATE TABLE `tk_paper_topic` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT,
  `paper_id` bigint(11) NOT NULL COMMENT '试卷id',
  `title` varchar(255) NOT NULL COMMENT '题目名称',
  `type` int(11) NOT NULL DEFAULT '1' COMMENT '题目类型 1选择题 2简答题',
  `select_num` int(11) NOT NULL DEFAULT '4' COMMENT '选择数量',
  `answer_type` int(11) NOT NULL DEFAULT '1' COMMENT '答案类型1文本2图片',
  `answer` varchar(4096) DEFAULT NULL COMMENT '答案',
  `answer_img` varchar(2048) DEFAULT NULL COMMENT '答案图片',
  `answer_img_back` varchar(2048) DEFAULT NULL COMMENT '答案图片备份',
  `operator` varchar(255) DEFAULT NULL COMMENT '操作人',
  `parsing` varchar(1024) DEFAULT NULL COMMENT '题目解析',
  `grade` int(11) NOT NULL DEFAULT '1' COMMENT '难度1简单2中等3难',
  `created_time` bigint(11) NOT NULL,
  `update_time` bigint(11) NOT NULL,
  `sort` int(11) NOT NULL DEFAULT '1' COMMENT '排序',
  `rel` int(11) NOT NULL DEFAULT '0',
  `del` int(11) NOT NULL DEFAULT '0',
  `parsing_type` int(1) DEFAULT '1' COMMENT '解析类型1文本/代码2图片',
  `parsing_img` varchar(1024) DEFAULT NULL COMMENT '解析图片',
  `parsing_img_back` varchar(1024) DEFAULT NULL COMMENT '解析图片备份',
  `err_msg` varchar(1024) DEFAULT NULL COMMENT '报错详情',
  `err_status` tinyint(4) DEFAULT '0' COMMENT '报错状态：0-无错误，1-有错误',
  `use_count` int(11) NOT NULL DEFAULT '0' COMMENT '组卷次数',
  PRIMARY KEY (`id`),
  KEY `idx_paper_id_rel_del` (`paper_id`,`rel`,`del`)
) ENGINE=InnoDB AUTO_INCREMENT=90673 DEFAULT CHARSET=utf8mb4 COMMENT='试题'