CREATE TABLE `tk_paper_new` (
  `id` bigint(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `edu_course_id` bigint(11) NOT NULL COMMENT '课程ID',
  `edu_course_exam_id` bigint(11) NOT NULL COMMENT '考试局ID',
  `edu_course_exam_subject_id` bigint(11) NOT NULL COMMENT '科目ID',
  `edu_course_exam_subject_name_id` bigint(11) NOT NULL COMMENT '科目名称ID',
  `edu_course_exam_module_id` int(11) DEFAULT NULL COMMENT '五级模块ID',
  `years` int(4) NOT NULL COMMENT '年份',
  `season_id` bigint(11) NOT NULL COMMENT '考试季id',
  `title` varchar(255) NOT NULL COMMENT '试卷名称',
  `title_origin` varchar(100) DEFAULT NULL COMMENT '试卷名称（自定义）',
  `grade` varchar(255) DEFAULT NULL COMMENT '年级',
  `admin_user_id` int(11) NOT NULL COMMENT '操作人ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `rel` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否发布',
  `deleted` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否删除  1已删除 0未删除  默认0',
  PRIMARY KEY (`id`),
  KEY `tk_paper_new_edu_course_id` (`edu_course_id`) USING BTREE,
  KEY `tk_paper_new_edu_course_exam_id` (`edu_course_exam_id`) USING BTREE,
  KEY `tk_paper_new_edu_course_exam_subject_id` (`edu_course_exam_subject_id`) USING BTREE,
  KEY `tk_paper_new_edu_course_exam_subject_name_id` (`edu_course_exam_subject_name_id`) USING BTREE,
  KEY `tk_paper_new_edu_course_exam_module_id` (`edu_course_exam_module_id`) USING BTREE,
  KEY `tk_paper_new_admin_user_id` (`admin_user_id`) USING BTREE,
  KEY `idx_subject_levels` (`edu_course_id`,`edu_course_exam_id`,`edu_course_exam_subject_id`,`edu_course_exam_subject_name_id`,`edu_course_exam_module_id`,`deleted`)
) ENGINE=InnoDB AUTO_INCREMENT=11070 DEFAULT CHARSET=utf8mb4 COMMENT='考卷（2025新版）'